### ISSUE TITLE
go through the neo apps list and add any usable apps to our index

### ISSUE THREAD

**Issue by shea256** [blockstack/app.co#10]
http://ndapp.org/

**Comment by shea256** [comment]
Potential candidates:

- https://neonexchange.org/
- http://neo-raffle.win/

We must confirm these are usable ^

**Comment by markmhx** [comment]
I've started a doc here to collect all content curation needs we have in mind, and I'm starting discussions internally around hiring an intern so we can have someone regularly help with site content: https://paper.dropbox.com/doc/App.co-Content-Needs--AIooRt0MXX4TEEYwP9gCo~aNAg-2UDg2X3AHyNkiSOkZw9eK
