### ISSUE TITLE
Gitcoin Logo + Description Update

### ISSUE THREAD

**Issue by vs77bb** [blockstack/app.co#11]
Hello - great work on App.co. I'm Vivek from Gitcoin and we'd like to update our logo + description. 

**Description**: Gitcoin makes it easier to incentivize or monetize work in open source software. 

Logo below! cc @owocki @mbeacom
![helmet](https://user-images.githubusercontent.com/23297747/40148910-112c56d4-5936-11e8-95df-aa9796b33bf3.png)

**Comment by hstove** [comment]
Thanks for letting us know! We've updated the listing.
