### ISSUE TITLE
Fix borders on app items

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#111]

**Comment by jeffdomke** [comment]
![screen shot 2018-08-13 at 3 35 09 pm](https://user-images.githubusercontent.com/767828/44053734-8407123e-9f0e-11e8-8070-78ae2f9ba5d7.png)
Still seeing some jank

**Comment by aulneau** [comment]
I'm opting to punt this as it's adding some complexity that seems like we can come back to later, lmk thoughts @jeffdomke
