### ISSUE TITLE
/categories and /platforms should be just a list of categories/platforms, no apps

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#112]

**Comment by jeffdomke** [comment]
What part of this is unclear please?

**Comment by hstove** [comment]
I think we should just have `/all` instead of `/categories/all` and `/platforms/all` if you want to actually view the global list of ranked apps. Agreed that `/categories` and `/platforms` should just be a list of categories/platforms.

**Comment by aulneau** [comment]
Yeah I agree, I think `/all` makes the most sense

**Comment by jeffdomke** [comment]
Yep agreed. Sorry this one got complicated.
