### ISSUE TITLE
Form elements are looking borked

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#113]
![Screen Shot 2018-08-13 at 7:48 PM](http://marker.screenshots.prod.s3.amazonaws.com/dd8d1ae3f72348b2be016e36b8dfc909-1534189736833.png)
---
### More Info

**Source URL**: [https://appco.now.sh/submit](https://appco.now.sh/submit)

**Comment by aulneau** [comment]
Seems to be working for me?
