### ISSUE TITLE
Populate empty categories with apps

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#114]
![Screen Shot 2018-08-13 at 8:01 PM](http://marker.screenshots.prod.s3.amazonaws.com/65b7ddaf36d244a18ae7093fb8f5bad1-1534190466152.png)
---
### More Info

**Source URL**: [https://appco.now.sh/platforms/bitcoin-cash](https://appco.now.sh/platforms/bitcoin-cash)

**Comment by jeffdomke** [comment]
Missing icons

**Comment by markmhx** [comment]
Currently empty categories:

- https://app.co/p2p-network
- https://app.co/0x-relays
- https://app.co/zeronet (once fake apps removed per https://github.com/blockstack/app.co/issues/217)
- https://app.co/bitcoin-cash
