### ISSUE TITLE
https://app.co/faq#about != https://appco.now.sh/faq need to redirect all those main pages from first site

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#120]
Need 301

**Comment by aulneau** [comment]
This doesn't need a 301, we just have to add an anchor on the content.

**Comment by hstove** [comment]
@aulneau is this possible with our markdown content? I guess we could just write straight HTML for that header, with an ID attr

**Comment by aulneau** [comment]
```
### [My Title](#my-title)

```

**Comment by aulneau** [comment]
oh wait maybe not!
