### ISSUE TITLE
Remove duplicate search clear button in Edge browser

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#122]
![Screen Shot 2018-08-14 at 4:33 PM](http://marker.screenshots.prod.s3.amazonaws.com/b3641b74eb88439299e0422b8b7ced2a-1534264392677.png)
---
### More Info

**Source URL**: [https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fapp.graphitedocs.com%2F&speed=1](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fapp.graphitedocs.com%2F&speed=1)

**Comment by markmhx** [comment]
By "Edge" does that mean this is a display bug found in the Edge browser?
