### ISSUE TITLE
Include .env-sample and config sample files

### ISSUE THREAD

**Issue by gaboesquivel** [blockstack/app.co#13]
Hi, I wanted to the site on my local. But there's no sample config dir or .env-sample file, so I wasn't able to run the migration or seed dummy data.

**Comment by hstove** [comment]
Hey! We actually moved the backend API to a separate repository. It's still private but I'll move it to public soon and let you know.

**Comment by markmhx** [comment]
@hstove any updates here as far as the other repo going public?

**Comment by hstove** [comment]
It's public! https://github.com/blockstack/app.co-api .
