### ISSUE TITLE
Add input validation to app submission form

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#134]

**Comment by hstove** [comment]
Forum discussion: https://forum.blockstack.org/t/suggestions-for-validation-of-app-co-submission-form/5976

**Comment by markmhx** [comment]
I've provided my feedback on the forum above. Though I'd recommend we bring the conversation back into this issue's comment thread (and for issues in general if the discussion maps well to them). That way we don't fragment the conversation and work too much.

**Comment by markmhx** [comment]
@hstove Can this issue be closed out given the most recent changes to this form?

**Comment by hstove** [comment]
@markmhx can you QA and close it if it's sufficiently fixed?

**Comment by markmhx** [comment]
@hstove Yep for sure. Okay to QA in production or is there a staging link that works so I don't inadvertently submit dummy data during my tests (repeatedly 😬)

**Comment by hstove** [comment]
https://staging.app.co/

**Comment by markmhx** [comment]
The "Did you build this app?" label's input requires a value but doesn't indicate ithats requirement with "(required)" as is indicated for other inputs.

<img width="794" alt="screen shot 2019-01-15 at 17 23 48" src="https://user-images.githubusercontent.com/28991/51213930-5b055200-18ea-11e9-8ed3-552d61d0fc40.png">

**Comment by markmhx** [comment]
We should also indicated "(required)" for these last two input labels for consistency:

<img width="850" alt="screen shot 2019-01-15 at 17 30 31" src="https://user-images.githubusercontent.com/28991/51214242-542b0f00-18eb-11e9-8cba-c8a5c0b33762.png">

**Comment by markmhx** [comment]
@hstove Assigning this back to you for the small corrections above. Please feel free to close once those are addressed since no additional review will be needed.

**Comment by aulneau** [comment]
I can take this

**Comment by aulneau** [comment]
this has been fixed with https://github.com/blockstack/app.co/commit/7acd9ee5c1a14f7b6ebabfd1d08c9c3dad7a5fee
