### ISSUE TITLE
No stats from similar web

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#137]

**Comment by hstove** [comment]
Can you clarify? Some apps are simply not available in similar web (the less popular domains)

![shot](https://dzwonsemrish7.cloudfront.net/items/3s2o083m3H232R1z301S/Screen%20Shot%202018-08-14%20at%2011.00.07%20AM.png?v=35d0741c)

**Comment by hstove** [comment]
We figured it out, it had to do with how Thomas's staging link was pulling data. Should be good now.
