### ISSUE TITLE
General form validation

### ISSUE THREAD

**Issue by aulneau** [blockstack/app.co#138]
In the browser we're using [Formik](https://github.com/jaredpalmer/formik) and [Yup](https://github.com/jquense/yup) to handle our form validation. I think it'd be great to use those in this project, too! Thoughts @hstove ?

**Comment by hstove** [comment]
I'm on board with that! I'm about to work on #134 and #131 , so I'll use those.

**Comment by markmhx** [comment]
Closing this out since it seems addressed by @hstove linked issues above.
