### ISSUE TITLE
/all should be a global ranked list of apps

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#140]

**Comment by hstove** [comment]
@jeffdomke how should we link to this page?

**Comment by jeffdomke** [comment]
Two ideas: 1) That top 10 list should just be the preview of that larger all list. 2) Add a link to header footer "All dapps"

**Comment by aulneau** [comment]
Yeah I think we should have a 'view all' button that goes to all, and also add it to the header and footer.

**Comment by hstove** [comment]
Right now there is a link in the footer to "All Apps", I should change it to "All Dapps"? And I'll add the 'view all' button on the home page list

**Comment by jeffdomke** [comment]
Sorry yep, I would add "All Apps" to both header and footer.
