### ISSUE TITLE
Janky email submit

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#141]

**Comment by jeffdomke** [comment]
![2018-08-16 16_10_11](https://user-images.githubusercontent.com/767828/44232417-ff823d00-a16e-11e8-8780-6c1a1cd5be0c.gif)

**Comment by jeffdomke** [comment]
Not fixed. I tap the arrow or hit return. It (seemly) freezes for 5 seconds then the whole thing vanishes. It appears to not be functional. Needs basic feedback: Submit causes some reaction. Maybe css transition.

**Comment by jeffdomke** [comment]
The first problem is gone. There is a new problem introduced: 
– Enter email
– Submit
– Wait for email box to vanish
– Reload page

Result: Email box appears for 1 second then disappears. 
Expected: It doesn't render at all.

**Comment by aulneau** [comment]
I think I know what caused the issue, when the server compression was removed, our cookies middleware was also removed by accident. I added it back in and it should solve the momentary flash of the newsletter box showing up when it should not. cc @hstove
