### ISSUE TITLE
Taping view more puts user in the middle of scroll list. Should reset to the top of that page.

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#143]

**Comment by jeffdomke** [comment]
Seems pretty non critical we can punt if this isn't easy. 

![2018-08-17 09_42_22](https://user-images.githubusercontent.com/767828/44269299-1b82ee80-a202-11e8-88a7-d4aa804a5ede.gif)

**Comment by markmhx** [comment]
This is generally one of my biggest pet peeves with SPAs =)

That said, I can't seem to recreate it – @jeffdomke are you still experiencing this functionality on your device?

http://g.recordit.co/sklaUV4Y9R.gif
