### ISSUE TITLE
Swap out the default pre-load with a darker color or gradient so this state is more useful. 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#145]
![Screen Shot 2018-08-17 at 1:48 PM](http://marker.screenshots.prod.s3.amazonaws.com/0d2f26c45a0448eeb85df7f97f00525e-1534513692341.png)
---
### More Info

**Source URL**: [file:///Users/jeffdomke/Downloads/IMG_0277.PNG](file:///Users/jeffdomke/Downloads/IMG_0277.PNG)

**Comment by aulneau** [comment]
this will be fixed when we have imgix working

**Comment by markmhx** [comment]
I've linked this issue to the imgix one so we can tackle it there and close this one out.
