### ISSUE TITLE
Footer links on mobile – recommend we stack them and center them

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#146]
![Screen Shot 2018-08-17 at 1:49 PM](http://marker.screenshots.prod.s3.amazonaws.com/398915423c0344f980f07d9e8fef0031-1534513756000.png)
---
### More Info

**Source URL**: [file:///Users/jeffdomke/Downloads/IMG_0278.PNG](file:///Users/jeffdomke/Downloads/IMG_0278.PNG)

**Comment by markmhx** [comment]
Closing this out since it appears complete:

<img width="414" alt="screen shot 2018-09-06 at 13 46 16" src="https://user-images.githubusercontent.com/28991/45155430-43e78280-b1db-11e8-955c-6feb04014b13.png">
