### ISSUE TITLE
Tapping the hamburger on iOS safari results in the last link being cut off — recommend we put these at the top of the screen the physical interaction is strange anyway. 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#147]
![Screen Shot 2018-08-17 at 1:51 PM](http://marker.screenshots.prod.s3.amazonaws.com/4e30a2def9a64e4f97e66e8ecc20eb6f-1534513894324.png)
---
### More Info

**Source URL**: [file:///Users/jeffdomke/Downloads/IMG_0279.PNG](file:///Users/jeffdomke/Downloads/IMG_0279.PNG)

**Comment by markmhx** [comment]
Closing this out since the items are showing up at the top of the viewport for me now:

<img width="421" alt="screen shot 2018-09-06 at 13 44 43" src="https://user-images.githubusercontent.com/28991/45155377-139fe400-b1db-11e8-818e-dda903319eb0.png">
