### ISSUE TITLE
Update FAQ copy for mining page

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#160]

**Comment by xanbots** [comment]
**FAQ**

What is Blockstack?
Blockstack is a new internet for decentralized apps that you access through the Blockstack Browser. With Blockstack, there is a new world of apps that let you own your data and maintain your privacy, security and freedom.

What is App.co?
The first ecosystem-wide, universal Dapp Store. App.co currently serves as an aggregator of usable dapps for gaming, social networking, productivity, and financial services. It is a discovery tool for decentralized apps built on Blockstack, Ethereum, EOS, IPFS, Steem, and more. 

How do App Rankings Work?
Each App Reviewer will be able to define the criteria used to rank applications. We will update everyone with more information as soon as possible.

How do Payouts Work?
Bitcoin is paid out each month to a list of top apps on Blockstack. Rankings are determined by a carefully selected group of app reviewers. We will update everyone with more information as soon as possible.

When will App Mining be live?
Q4 2018. We will update everyone with more exact timing as soon as possible.

**Comment by xanbots** [comment]
cc @pstan26 for sign off
