### ISSUE TITLE
Fallback images before image loads

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#168]

**Comment by hstove** [comment]
@jeffdomke I hope you don't mind me assigning this to you. @larrysalibra pointed out that some app images didn't load for him. I'm assuming this is some networking error, I know he's in HK so there isn't a firewall (right?) but we should have some fallback image for when the image is loading or fails to load. Can you design this? Or, we can just make it a gray box.

Also, hopefully the networking issue is fixed/improved when we move to imgix. Some images just are slow to load.

**Comment by markmhx** [comment]
What images in particular are failing to load? App logos?

**Comment by larrysalibra** [comment]
Yes. Right now just Dappy and Stealthy app images which look like they're hosted on dropbox and twitter respectively.

On Safari on my computer, stealthy loads but dappy's image doesn't.

<img width="1297" alt="screen shot 2018-08-21 at 7 39 36 pm" src="https://user-images.githubusercontent.com/597182/44399434-28913c00-a57a-11e8-8e7b-a814f70e1451.png">

On chrome on my mac, both images load.

Might have something to do with the `text/html` redirect that dropbox returns when requesting the image URL:

```
curl -I https://www.dropbox.com/s/1047ee84pgzn9tf/ic_dappy_radius.png?dl=1
HTTP/2 301 
server: nginx
date: Tue, 21 Aug 2018 11:43:06 GMT
content-type: text/html; charset=utf-8
cache-control: no-cache
content-security-policy: sandbox
location: /s/dl/1047ee84pgzn9tf/ic_dappy_radius.png
pragma: no-cache
referrer-policy: origin-when-cross-origin
set-cookie: locale=en; Domain=dropbox.com; expires=Sun, 20 Aug 2023 11:43:06 GMT; Path=/; secure
set-cookie: gvc=NzkwNjE3NzUzNjQyOTI4NjkwODQ1NTY5NDIzNTUzNDcwNzg1Mjk%3D; expires=Sun, 20 Aug 2023 11:43:06 GMT; httponly; Path=/; secure
set-cookie: flash=; Domain=dropbox.com; expires=Tue, 21 Aug 2018 11:43:06 GMT; Path=/; secure
set-cookie: puc=; expires=Tue, 21 Aug 2018 11:43:06 GMT; httponly; Path=/; secure
set-cookie: bang=; Domain=dropbox.com; expires=Tue, 21 Aug 2018 11:43:06 GMT; Path=/; secure
set-cookie: t=8TzbDjTIgg7hGL3IPBPanEAz; Domain=dropbox.com; expires=Fri, 20 Aug 2021 11:43:06 GMT; httponly; Path=/; secure
set-cookie: __Host-js_csrf=8TzbDjTIgg7hGL3IPBPanEAz; expires=Fri, 20 Aug 2021 11:43:06 GMT; Path=/; secure
x-content-type-options: nosniff
x-dropbox-request-id: 716623afb1abf7f75076ad13cece56c7
x-frame-options: DENY
x-robots-tag: noindex, nofollow, noimageindex
x-xss-protection: 1; mode=block
strict-transport-security: max-age=15552000; includeSubDomains
```

**Comment by markmhx** [comment]
Thanks, that sounds like a likely culprit with Dropbox at least.

We're planning on integrating imgix as a cache in https://github.com/blockstack/app.co/issues/90 so I've just increased its scope to include a default image, which I think we can provide as a simple transparent pixel since that way we simply don't show any logo in the error case.

I'm closing this issue out in favor of that other issue.
