### ISSUE TITLE
Fix registration modal sizing on mobile

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#169]
@larrysalibra pointed out that the app mining registration modal is broken on mobile.

As part of this, we need to also change the `email` input to be `type="email"` so that its a better experience on mobile.

**Comment by markmhx** [comment]
How is the modal broken exactly?

**Comment by larrysalibra** [comment]
@markmhx https://forum.blockstack.org/t/app-co-feedback-please/6042/5?u=larry

>  the modal behaves very strangely on my phone (IPhone X - Safari). Top of form gets cut off and when I try to scroll, the form doesn’t move but the background scrolls.


![](https://forum.blockstack.org/uploads/default/original/2X/9/912ab495bb0dd58b099abf01e64f5c8f4c1fee26.jpg)
