### ISSUE TITLE
Remove text underline from search results

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#172]
<img width="679" alt="screen shot 2018-08-21 at 17 05 56" src="https://user-images.githubusercontent.com/28991/44410366-861a8e00-a564-11e8-936c-6c7aecacba52.png">

**Comment by aulneau** [comment]
I'm curious as to why you want this removed? it is a link, and I think the underline is valuable to the end user.

**Comment by markmhx** [comment]
Underlining links (or otherwise distinguishing them from surrounding text, such as with bolding) is useful especially when those links are embedding in paragraphs or other contexts where its not obvious given the context that the text is clickable. But here in search results with such minimal information, it's clear that the apps we're showing as results are all clickable even without the underline, so it becomes extraneous.

And given that the search result app unit is formatted very similarly to app listings across the site, the underline is a jarring difference.

Note how much this search result:

<img width="555" alt="screen shot 2018-08-22 at 10 25 44" src="https://user-images.githubusercontent.com/28991/44452041-bf4f0e80-a5f5-11e8-8d47-525d4ec1dbb1.png">

Looks almost identical to this listing without the underline:

<img width="399" alt="screen shot 2018-08-22 at 10 25 47" src="https://user-images.githubusercontent.com/28991/44452058-c70eb300-a5f5-11e8-9fb9-3028c5261cea.png">

So, the goal in this particular case is mainly consistency.
