### ISSUE TITLE
Improve text formatting on FAQ page

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#174]
- Line height of 1.5em for all paragraph and list items tags (p, li)
- Top margin of 64px for all header1 (h1) tags apart from the first on the page
- Bottom margin of 1em for all header1 (h1) tags
- Top margin of 1em for all list item tags (li)
- Top margin of 2em for all unordered or ordered lists tags (ul, ol)

<img width="1204" alt="screen shot 2018-08-21 at 17 20 27" src="https://user-images.githubusercontent.com/28991/44411352-93d11300-a566-11e8-874f-3ef85dfc87f9.png">
<img width="465" alt="screen shot 2018-08-21 at 17 20 47" src="https://user-images.githubusercontent.com/28991/44411350-93d11300-a566-11e8-86ac-032aa31fd979.png">

<img width="448" alt="screen shot 2018-08-21 at 17 20 55" src="https://user-images.githubusercontent.com/28991/44411349-93d11300-a566-11e8-9bcd-21cef4efb473.png">

**Comment by aulneau** [comment]
@markmhx Thanks for these specific units! This page def needs some typographic love. I do want to point out that we are using this thing called `styled-system` which uses this theme object -> https://github.com/blockstack/app.co/blob/feature/update-design/common/styles/index.js#L53 to pull from when setting up spacings etc. 

I think we should avoid `em` units and defer to this organization/units. It allows us to do things like `<Type.h2 mt={[3, 4]} {...props} />` which would give us a margin top of 12px on mobile and 24px on anything larger. Avoiding custom usages of `2em` etc will help us stay more consistent throughout the design (I think this page was just an afterthought / hasn't been deeply looked at yet).

**Comment by aulneau** [comment]
This page is also using `mdx` which will allow us to pass in custom components for rendering the markdown, which I am doing here -> https://github.com/blockstack/app.co/blob/feature/update-design/components/mdx/index.js#L6, currently we're automatically taking the content of the text and turning into an id so we can link to pages like `/about#faq` etc.

**Comment by markmhx** [comment]
Thanks for the heads up regarding styled-system usage. It seems the units system it uses for sizing relative to font size is documented here: https://github.com/jxnblk/styled-system/blob/master/docs/api.md#fontsize

However, it's not clear to me how it works exactly given the link there to "font size scale" is broken. At the bottom of the documentation, there's a "Font Sizes" section that seems to suggest that the 0-8 system maps to these pixel values: 

> [ 12, 14, 16, 20, 24, 32, 48, 64, 72 ]

It seems our base font size is 16px, so 2em for example would be converted to value "5", correct? I'm cool with that in that I have no attachment to using em per se, but just want to be clear here so I provide accurate guidance going forward.

The latest changes on staging look generally good and correspond well to the guidance. However, I would make these further refinements:

- Top margin for h1s should be value 7 instead of 8
- Top margin for *first child tag* h1 should be none
- Top margin for li should be 2 instead of 6px on top and bottom for margins

Note how removing the top margin for the first h1 tag on the page will cram it to the top of the white area, but that issue should be resolved with https://github.com/blockstack/app.co/issues/47 since it's best to define the white area / content container's inner padding on its own element instead of trying to ensure it by setting its children's margins, which are prone to vary.
