### ISSUE TITLE
Broken state with search

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#180]
1. Search for Stealthy
2. Tap on result for Stealthy
3. In modal, tap on tag such as `Blockstack`

Result: `Blockstack` results load behind the modal and search. And, user cannot scroll on that page. 
Expected: Clicking on the tag loads fresh page of results with no state/issues.

**Comment by markmhx** [comment]
Same as this one? https://github.com/blockstack/app.co/issues/171

**Comment by jeffdomke** [comment]
Checked, this is something different.

**Comment by markmhx** [comment]
Just trying to beat you to the draw ;)

**Comment by markmhx** [comment]
Looks like this was the same as https://github.com/blockstack/app.co/issues/175 after all and is resolved now.
