### ISSUE TITLE
Remove minimum height from category headers

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#181]
<img width="432" alt="screen shot 2018-08-21 at 18 01 59" src="https://user-images.githubusercontent.com/28991/44413697-4fe10c80-a56c-11e8-8dea-8d7f9dda8e60.png">
<img width="1225" alt="screen shot 2018-08-21 at 18 01 53" src="https://user-images.githubusercontent.com/28991/44413698-4fe10c80-a56c-11e8-9f3b-8a47c18e5584.png">

**Comment by aulneau** [comment]
Can you go into more detail as to why you want this @markmhx? @jeffdomke has been pretty adamant about having the headers be a specific size to fit the graphics we have.

**Comment by jeffdomke** [comment]
Look at the figma. The designs make sense, trust me I do this for a living :) I'm fine with changing the designs, but want to do so with full consideration around how the illustrations, view more buttons, etc. all collide (or don't collide). In this particular case, this category could require view more button at any moment in the future.

**Comment by markmhx** [comment]
I'm closing this out in favor of https://github.com/blockstack/app.co/issues/200, which takes precedent as a higher-level concern and if executed, will nullify this issue's concern.
