### ISSUE TITLE
Invalid image format: Karma

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/app.co#195]
App "karma" is using an image format webp that as of now only works on Chrome. https://caniuse.com/#search=webp

https://static.wixstatic.com/media/4bd50a_1c463d0fa7c94925b5ebb6314b0c756d~mv2.png/v1/fill/w_101,h_101,al_c,q_80,usm_0.66_1.00_0.01/4bd50a_1c463d0fa7c94925b5ebb6314b0c756d~mv2.webp

**Comment by markmhx** [comment]
Yeeks, well it looks as though imgix can convert formats so we should make sure we use that functionality to convert all images to a commonly supported format: https://docs.imgix.com/apis/url/format/fm

I've added this requirement to https://github.com/blockstack/app.co/issues/90 so we can tackle it during our initial imgix implementation.
