### ISSUE TITLE
Add a second category for biz tools

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#20]

**Comment by hstove** [comment]
Here is a list of proposed apps:

- Aragon
- Graphite
- Gitcoin
- Bounty0x
- adChain Registry
- ETHLance

Please comment if you think any should be removed / added. Right now our design supports exactly 6 apps, but in the future it will be more dynamic.

**Comment by shea256** [comment]
+1 Nice list. Surprised there aren't actually more of these right now. Was going to say we could add Gems as well but it currently doesn't look like it has many jobs or activity once you sign in. So current list looks perfect.
