### ISSUE TITLE
Show tweets for apps

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#202]
We show the total number of tweets about an app each week but it'd be even more valuable to show the actual tweets.

**Comment by hstove** [comment]
An 'easy' way to buff the app page, given the data we have currently, is to show recent tweets and some historical stats on tweets and web traffic data. Also your thought about a 'long description' field, and more dynamic URLs

**Comment by markmhx** [comment]
How many recent tweets are we currently pulling? Is there a max?
