### ISSUE TITLE
Investigate 'Learn More' modal possibly not opening across browsers

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#213]

**Comment by markmhx** [comment]
@hstove Did you originally create this as a task and is the problem immediately confirmable in at least one browser? If not, I'd suggest we close this until we can recreate specifically.

**Comment by hstove** [comment]
I created it because Gina brought it up in the forum thread around internal feedback. I've never repro'd it, and no one else has, and I think it's working for her now. Closing!
