### ISSUE TITLE
Add extensible URLs model for apps

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#215]
This would entail allowing us to add any number of URLs for an app, providing both the URL value and a name. For example, this could be used to variably add the following and any others:

- Twitter
- Facebook
- GitHub
- Dribbble
- Website
- iOS App Store
- Google Play Store
- Telegram

The model would basically just have "name" and "url" and relate to apps in the database, and we'd query it to show any for a given app on its profile page.

**Comment by aulneau** [comment]
Yeah, I think we should also just create a convention for what we want as the URL. I think currently it's a mix between the marketing website and the actual app url.

**Comment by markmhx** [comment]
My gut tells me that marketing website is better since its usually singular whereas app URLs can vary and multiply (e.g. web, iPhone, Android, etc).

**Comment by markmhx** [comment]
Perhaps a small issue to break off from this one is to simply update the "Add app" form to provide this sort of guidance?

**Comment by hstove** [comment]
Product Hunt is a good model for this. When you see an app that has multiple links (like multiple mobile apps), there is a dropdown with explicit names for stuff like "iOS App".
