### ISSUE TITLE
Create a sample application category in App.co

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#250]
For OKR 2, the walk a developer through end-to-end, we need a category on App.co where users can drop their completed sample application.  See the forum for detail on the outline.

So, when they add their Dapp to app.co they can get a sense of completion.  Also, adds a category where users can see how many people completed the samples.

This category shouldn't come up in a regular search of app.co and could perhaps be displayed on a special page: "see who has tried our tutorial" or something.

**Comment by pstan26** [comment]
Thank you for adding this Mary

**Comment by markmhx** [comment]
@hstove can we add this category easily without listing it on the homepage?

**Comment by markmhx** [comment]
@moxiegirl Do you have a preference for what we call this category (e.g. "Sample Blockstack apps")? And mind providing a link to the forum content you mention?

**Comment by moxiegirl** [comment]
@markmhx the forum is in private space so I didn't link it here. It is linked in your recent App.co OKR doc.   **Animal Kingdom App** would be my preferred name for the category. Just having that as a category name would be a bit of whimsy which I think is fine. Also, a name like that would encourage people to look at it --- if they didn't know what was already.

Non-whimsy, your "Sample Blockstack Apps" would work also.

@hstove OK. So we don't have to worry about it showing up on the home page. 👍  Discoverability could actually be handled by the tutorial.  In other words, the last page has them adding the application to app.co.  I can put a link to the category from the tutorial.  Then, perhaps at some point from App.co we can "advertise" the category **Visit the Animal Kingoms** or a mention.

**Comment by markmhx** [comment]
I don't think it's a big deal if this category shows up on the categories page, but @hstove feel free to tweak the code to hide it if you want.

**Comment by moxiegirl** [comment]
@markmhx @jeffdomke This is the one issue that we need to get completed so that the Zero to Dapp tutorial can go live.  

cc: @pstan26

**Comment by moxiegirl** [comment]
Just to be clear the task is:

- Category "Sample Blockstack Application" should appear in the drop down -- last is fine
- A Sample Application category page should be available that lists these so users can check.  
- This page should not appear on as a category on the home page or return from the search
-  This page should be able to be linked to either thru search or via a dedicated link

**Comment by hstove** [comment]
Hey Mary, this is updated and should be deployed in around 10 minutes. I didn't hide it from our Categories page: https://app.co/categories , which I think is fine right now. We can always hide it later if we choose to.

**Comment by moxiegirl** [comment]
Wonderful! Thanks @hstove for the super quick turnaround.
