### ISSUE TITLE
Provide input for collecting repository URL in App Mining registration form

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#259]
A new input for "Public repository" should appear when the user selects "Yes" for "Does your app have Blockstack Auth implemented?" in the App Mining registration form upon selecting "Register for App Mining" on https://app.co/mining.

This input should be displayed below the above prompt and above the "Submit" button. Its placeholder text should be "https://github.com/developer/app". The field should be *optional* and the value entered should be stored alongside the rest of the registration data in our database.

<img width="778" alt="screen shot 2018-10-15 at 11 50 50" src="https://user-images.githubusercontent.com/28991/46943747-9e90bb80-d070-11e8-99db-6c41bbb50496.png">

Requested by @xanbots

**Comment by aulneau** [comment]
@hstove I've added this to the frontend as an optional field. the key I chose is `repo`

**Comment by aulneau** [comment]
![screen shot 2018-10-16 at 12 33 28 pm](https://user-images.githubusercontent.com/11803153/47035839-8c7e4e00-d140-11e8-9979-04cc9d6340b5.png)

@markmhx I've opted to keep the input above the radio buttons as it felt out of place. I also think a placeholder of `Public Repository (GitHub, etc)*` makes more sense and is consistent with how we are using our other labels as placeholders.

**Comment by markmhx** [comment]
@aulneau Those are good improvements 👍🏻

As a result, though, we should probably just show the public repository input regardless of whether the user toggles "Yes" for the Blockstack Auth prompt, since it would be strange to reveal an input *above* that prompt.

**Comment by aulneau** [comment]
Yep! That's how it currently functions
