### ISSUE TITLE
Add reviewer names for App Mining Alpha Run

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#276]
The following section of the monthly results page should show the names of Democracy Earth and Product Hunt instead of Reviewer #1 and #2:

<img width="500" alt="screen shot 2018-10-16 at 13 26 13" src="https://user-images.githubusercontent.com/28991/47013342-22b57280-d147-11e8-89a3-5c4ce18b3df2.png">

**Comment by hstove** [comment]
OK, but then we need to have some kind of heading that says 'reviewers'. Otherwise its just a list of companies with no context.

**Comment by jehunter5811** [comment]
I have a feeling this announcement will drive a good amount of traffic. It'd be good to have the app name link out to the app's site.

**Comment by hstove** [comment]
@jehunter5811 that link is not ready and was not meant to be shared publicly. @markmhx please don't do that, we have staging links :). It's unpublished now.

**Comment by markmhx** [comment]
@hstove Whoops, my bad! Perhaps we need password protected staging links for cases like this one?

@jehunter5811 We're going to be linking to the apps' profiles on app.co from this page and from there visitors can click over to the apps' websites. We're hoping this drives traffic to developers and will check our analytics post-launch to see how it goes. But as @hstove said, we're not quite at launch yet 😬

**Comment by markmhx** [comment]
@hstove Also that's a good point that we don't introduce these reviewer sections at all. I think I missed the forest for the trees there.

Perhaps we can simply suffix their names with "reviewer notes" e.g. "Product Hunt reviewer notes"?

Or perhaps better, above the reviewer sections, we place a line such as "Product Hunt and Democracy Earth contributed app rankings for the generation of this month's results." Think that's even better?

**Comment by hstove** [comment]
> Perhaps we need password protected staging links for cases like this one?

No, I think it's fine to link to our staging links publicly. The data is all fake, which was the important thing we wanted to prevent from being shared.

The thing about including "Reviewer notes" is that we don't have any reviewer notes from them.

To be honest, I like it how it is with "Reviewer #1, Reviewer #2". I think that's pretty clear.

**Comment by aulneau** [comment]
> To be honest, I like it how it is with "Reviewer #1, Reviewer #2". I think that's pretty clear.

I agree

**Comment by markmhx** [comment]
I think the way it is now is fine for launch. I may take a stab at improving this soon though.
