### ISSUE TITLE
Fix typography fonts

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#278]
Since we've updated the site to use `blockstack-ui`, all of our body-style typography components have a broken font. I've brought that up here: https://github.com/blockstackpbc/blockstack-ui/issues/2

Unfortunately I can't update the `blockstack-ui` library because I'm not an npm collaborator (but could you add me).

This is visible anywhere we use something like `Type.p`, such as on the public results page.

**Comment by aulneau** [comment]
Should be fixed now @hstove
