### ISSUE TITLE
Add quote from Nick Tee, creator of Blockusign to app mining landing page

### ISSUE THREAD

**Issue by pstan26** [blockstack/app.co#286]
"App rewards mining allows Blockusign to focus on what we do best, BUILD!  It provides us with the extra incentive to keep forging ahead and iterating in this brand-new ecosystem - without having to worry about finding early stage funding. We truly feel included in this passionate community of people, from around the world, that believe in building the decentralized open web."

**Comment by aulneau** [comment]
@pstan26 can you provide a photo for Nick Tee, too? Thanks!

**Comment by pstan26** [comment]
He's looking for a better one without a tie.. but for the time being here's this: https://media.licdn.com/dms/image/C5103AQEZvKJpyBOWQA/profile-displayphoto-shrink_200_200/0?e=1545264000&v=beta&t=oAEkyXGypK4ZrudHY8x-tPvw137PwgkE7klE_BU4V-8

**Comment by markmhx** [comment]
Looks good but I think we need to remove Thomas's as part of this addition, correct @pstan26?

**Comment by aulneau** [comment]
For what reason @markmhx ?
