### ISSUE TITLE
Reverse use of asterisks in App Mining qualification form 

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#289]
Currently we use an asterisk to indicate fields that are optional, but we should use them to indicate fields that are required since that's standard.

<img width="678" alt="screen shot 2018-10-18 at 11 38 44" src="https://user-images.githubusercontent.com/28991/47145608-64baf180-d2ca-11e8-89b3-292940083be0.png">

**Comment by aulneau** [comment]
I think it's pretty standard to only asterisk/declare the optional field if the rest of the form is required, generally it's agreed upon to be better ux to have only one optional indicator in place of many required indicators. https://www.formulate.com.au/blog/required-versus-optional-fields-new-standard

**Comment by markmhx** [comment]
If we don't want to add the asterisks everywhere else, I like Luke's suggestion there to "just add (optional)" to fields that are optional.

An asterisk for "optional" IMO is super confusing since it's traditionally used to indicate required / the opposite.

**Comment by markmhx** [comment]
No worries, that makes sense. Perhaps we should remove the parenthesis mentioning examples since developers are likely to understand the field without them? 

i.e. `Public repository URL (optional)`

**Comment by markmhx** [comment]
Confusion about the current use of an asterisk for this field appears to have been reported here: https://forum.blockstack.org/t/private-repository-in-app-co-signup-form/6636
