### ISSUE TITLE
"View all Apps" button on /mining doesn't work on firefox and looks weird

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#292]

**Comment by hstove** [comment]
The issue with the button is that it only works if you click the text of 'view all apps'. the entire button is not a link. Also, it's displayed weirdly because the icon is too big.

**Comment by markmhx** [comment]
The visual styling appears to be corrected in Firefox but the issue with the entire button not being a link is still outstanding.

<img width="1153" alt="screen shot 2018-10-19 at 14 14 46" src="https://user-images.githubusercontent.com/28991/47217678-60b1d100-d3a9-11e8-8e10-3b66ebd3c99b.png">
