### ISSUE TITLE
On /mining, we still say "reviewers will be announced soon", even though we list them in the FAQ

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#293]

**Comment by jeffdomke** [comment]
I have the original designs for this section I can update the copy and reviewers shortly.

**Comment by markmhx** [comment]
This appears to have been addressed:

<img width="1220" alt="screen shot 2018-10-19 at 14 16 09" src="https://user-images.githubusercontent.com/28991/47217716-88a13480-d3a9-11e8-9fc2-7549e08bf08d.png">
