### ISSUE TITLE
Update opengraph and twitter card

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#295]
![appmining](https://user-images.githubusercontent.com/767828/47167727-296df200-d2cd-11e8-9d26-e8f10d591ae1.jpg)

Not ideal, but should probably be this until we have something better

**Comment by markmhx** [comment]
Do you mean just for the `/mining` path and all sub-paths?

**Comment by hstove** [comment]
I don't recall unassigning myself here - I'll add it back.

**Comment by jeffdomke** [comment]
I meant we need to update the description and remove the goofy image.

**Comment by aulneau** [comment]
> remove the goofy image.

Which image is the goofy image?

> update the description

What should the description be?

The description is 

> Earn cash for apps you build with Blockstack. We are funding decentralized app teams simply for being pioneers in the space.

and I updated the image to the one that you posted -> https://user-images.githubusercontent.com/767828/47167727-296df200-d2cd-11e8-9d26-e8f10d591ae1.jpg

**Comment by jeffdomke** [comment]
Haha. I posed that 90 days ago. I would just synthesize a nice looking image from the logo / landing page. 

@cuevasm is the most up to date language we have? Seems out of date to me. 

The "cash" term. And "pioneers in the space" seems odd. This seems better IMO: 

> Every 30 days we payout $100k to the best apps build on Blockstack. The better your app, the more you earn.

**Comment by aulneau** [comment]
fixed!

**Comment by jeffdomke** [comment]
Not seeing this on stage?
