### ISSUE TITLE
Add code for Drift chat client to the site

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#302]
We're testing this as a way to help developers get more information quickly about App Mining.

`
<script>
"use strict";

!function() {
  var t = window.driftt = window.drift = window.driftt || [];
  if (!t.init) {
    if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
    t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
    t.factory = function(e) {
      return function() {
        var n = Array.prototype.slice.call(arguments);
        return n.unshift(e), t.push(n), t;
      };
    }, t.methods.forEach(function(e) {
      t[e] = t.factory(e);
    }), t.load = function(t) {
      var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
      o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
      var i = document.getElementsByTagName("script")[0];
      i.parentNode.insertBefore(o, i);
    };
  }
}();
drift.SNIPPET_VERSION = '0.3.1';
drift.load('46aa9a6p5e2d');
</script>
`

**Comment by cuevasm** [comment]
ASAP please, sales team is ready to use it right away and should only be a 2 minute task. I might suggest we get on Google Tag Manager if we can't do things like this relatively quickly. Thanks!

**Comment by hstove** [comment]
Google tag manager would be great. I'll do this today
