### ISSUE TITLE
Add email collection form to App Mining page

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#303]
The form will collect email addresses from visitors in exchange for sending them the list of reward recipients each month.

<img width="1393" alt="screen shot 2018-10-30 at 13 34 13" src="https://user-images.githubusercontent.com/28991/47718554-02a6a880-dc49-11e8-8ae7-4fb70b13b461.png">
<img width="1390" alt="screen shot 2018-10-30 at 13 36 45" src="https://user-images.githubusercontent.com/28991/47718555-033f3f00-dc49-11e8-87d7-0d486a343f12.png">

**Comment by larrysalibra** [comment]
"The better your app, the more Bitcoin you earn" -> this sounds developer focused...strange to continue reading the page and have the focus turn to consumer. What about "The better the app, the more Bitcoin it earns." You might also consider removing the word bitcoin from the heading.

**Comment by markmhx** [comment]
@pstan26 I'm assigning this to you since I think the main question at this point is whether you'd like to move ahead with a custom form like this or simply test the chat widget integration for now for base interest and email capture.
