### ISSUE TITLE
Add blog link to navigation

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#305]
It should be the last option in both the header and footer navigation components.

Requested by @GinaAbrams and @cuevasm

**Comment by cuevasm** [comment]
Hey how can we get this moved up the list?

**Comment by markmhx** [comment]
@cuevasm I've moved it to the "New Issues" column in ZenHub so we can consider it for the next sprint

**Comment by markmhx** [comment]
@aulneau I've included this issue in the sprint starting today with your assignment. Please let me know if it doesn't fit given your overall sprint workload.
