### ISSUE TITLE
Add header to app submission page

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#308]
The page where a user has to **Add a app** has no title.  This looks really odd.

Given the instructional text at the top, the verb Submit seems more appropriate for the title

**Submit your app to App.co**

If you do this, you should change the menu item to match **Submit your app** rather than **Add your app**.

**Comment by markmhx** [comment]
To be clear – I think you're referring to the addition of a header in the body about the form, not a title for the HTML page.

**Comment by moxiegirl** [comment]
@markmhx Yes, I think the page needs a heading.

**Comment by jeffdomke** [comment]
Add your app to App.co
