### ISSUE TITLE
Add labels to app submission form

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#310]
Not clear why there is no Blockstack or Stacks in the Blockchain category.

Also, the options in general need labels --- as it stands now these fields are not clear if they are labels or default values. They appear to be labels but I wouldn't blame users for assuming they are defaults.  

![image](https://user-images.githubusercontent.com/1347209/48984704-2926fa80-f0b4-11e8-8a5b-d7a89d1cacc9.png)
Once a user scrolls away from the "label" view, you have to refresh to get the labels back --- really odd behavior.

**Comment by markmhx** [comment]
@kantai @jcnelson Do you think it makes sense to add "Blockstack" or "Stacks" as a blockchain option here now or later on?

**Comment by moxiegirl** [comment]
@markmhx I think the larger issue is the lack of actual labels. This is a UX issue for sure.
