### ISSUE TITLE
Create an app mining ready page which displays apps shown here: https://app.co/mining/developer-instructions

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#313]

**Comment by jeffdomke** [comment]
Would suggest the page also contains a link to developer instructions docs.

**Comment by jeffdomke** [comment]
@aulneau can we sync about this. What are you thinking?

**Comment by jeffdomke** [comment]
The easiest solution is just delete the instructions but a page with some mods is in the figma

**Comment by aulneau** [comment]
Woah sorry for missing this!

I can easily display these apps in the new page. I'm a little unclear on what the use of a separate page would be? I think we can add a section to `/mining` that shows the next batch of apps. I think a whole page just for this would be pretty sparse. Additionally, where are we linking from to get to the page?

**Comment by jeffdomke** [comment]
Not seeing the page. Also this link: 

`Want to verify your app is completely registered? A list of all App Mining Ready apps.` should point to that page.

**Comment by jeffdomke** [comment]
@aulneau can you confirm how to test this? Not seeing the page and link isn't working?

**Comment by aulneau** [comment]
https://app-co-staging-pr-335.herokuapp.com/mining/apps

Sorry should not have moved this to review, still waiting on some data from the API.

**Comment by moxiegirl** [comment]
@GinaAbrams @aulneau Is this page necessary? We have this: https://docs.blockstack.org/develop/mining_enroll.html

Or, we can use the instructions there for this page.  Already reviewed and live what I have on the docs.

**Comment by GinaAbrams** [comment]
@moxiegirl it is [this page](https://app.co/mining/apps).
