### ISSUE TITLE
Integrate fullstory

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#316]

**Comment by cuevasm** [comment]
I'm a fan of this and like Fullstory, there was some hesitation before because of how much it tracks. No longer an issue?

**Comment by markmhx** [comment]
Assuming @cuevasm's concern is address, I'd recommend we set up FullStory as a Segment integration, not a code-based one: https://github.com/blockstack/app.co/issues/317

I'm closing this out with that in mind, while updating the other issue. But feel free to reopen if this approach should be discussed further.
