### ISSUE TITLE
Add links for 'Start App Mining' section

### ISSUE THREAD

**Issue by aulneau** [blockstack/app.co#323]
![screen shot 2018-12-06 at 9 24 34 am](https://user-images.githubusercontent.com/11803153/49593291-cac20d80-f938-11e8-8302-45c2b3488a31.png)

This section needs links for the three steps, and the two links below. @jeffdomke or @moxiegirl can you please reply here with the links to each?

**Comment by aulneau** [comment]
pinging @jeffdomke @moxiegirl @GinaAbrams to make sure you see this.

**Comment by GinaAbrams** [comment]
Build your app and integrate auth: [Zero to Dapp](https://docs.blockstack.org/develop/zero_to_dapp_1.html)

Register your app on app.co: [App.co/submit](https://app.co/submit)

Improve should go to the rankings (either in the page, or previous month?) 

[App Mining Docs](https://docs.blockstack.org/develop/mining_intro.html)

and is the last one the [developer instructions page](https://app.co/mining/developer-instructions)? Where else does that info live, if anywhere? cc @hstove

**Comment by aulneau** [comment]
I feel like the 'improve' link/button is questionable. @jeffdomke what were your thoughts behind it?

**Comment by jeffdomke** [comment]
Yeah, I agree it is confusing. The origin is the slide deck research. These three titles/names were validated and devs did get these three topics as the big things they need to do. So the wording/idea is correct, it just gets tricky as both CTA and heading. 

The original intention is that it should go to `/mining/latest`

**Comment by jeffdomke** [comment]
Send to /mining/apps
