### ISSUE TITLE
Add logo to app mining page

### ISSUE THREAD

**Issue by aulneau** [blockstack/app.co#324]
![screen shot 2018-12-06 at 9 26 52 am](https://user-images.githubusercontent.com/11803153/49593399-15dc2080-f939-11e8-8140-77b76b72df33.png)

I held off on adding the logo here because I was under the impression that we were going to rethink or change it from what was in the figma. cc @jeffdomke

**Comment by jeffdomke** [comment]
I don't have time nor do I think it is important. If you want to take a stab at it, great, but also suggest this would be low priority for your time. If you want to fallback to the outlined blockstack logo we use on wallet page, and elsewhere that could also work I think.
