### ISSUE TITLE
Add blockstack related tags to app items in ranking list on app mining

### ISSUE THREAD

**Issue by aulneau** [blockstack/app.co#327]

**Comment by jeffdomke** [comment]
![screen shot 2018-12-07 at 3 09 20 pm](https://user-images.githubusercontent.com/767828/49670280-1e645200-fa32-11e8-84fb-2c3d46c032df.png)

These should be pretty subtle. Played around with the colors a bit. New proposal: Same color as section bg and same body text color or maybe same at 75%?

**Comment by jeffdomke** [comment]
Also think should add some more padding to these.

**Comment by aulneau** [comment]
Yeah I agree, will modify
