### ISSUE TITLE
Add animations for app mining page

### ISSUE THREAD

**Issue by aulneau** [blockstack/app.co#329]

**Comment by jeffdomke** [comment]
Suggestion: For launch of this page, the animation at the top of the page seems far more important. Would prioritize that one or even just swapping out the info in a carousel

**Comment by aulneau** [comment]
yeah will work on it. the ideal thing we want is somewhat complex, will try to simplify

**Comment by jeffdomke** [comment]
This seems pretty near what I imagined. Why does the top card go backwards in 3D space? I assumed it would move ward, then dissolve. Then a new card would materialize at the back of the stack. Feel free to wave me off it too challenging, this will work for MVP.

**Comment by aulneau** [comment]
> Then a new card would materialize at the back of the stack. Feel free to wave me off it too challenging

Yes ideally but it's hard to do. What we have now will be for MVP and then we can work and improve it over time.
