### ISSUE TITLE
Subscribe to updates button

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#333]

**Comment by jeffdomke** [comment]
Intention here is that this is a button and it would trigger the same email capture and flow as registration. Even people who are passively interested we will share the kit, then prompt them to go learn to build an app. Open to something else, but wanted to make note.

**Comment by aulneau** [comment]
ah cool ok, I interpreted it as an input like we have in other properties. I think I don't really see the advantage of:

- hit button
- enter email
- submit email
- modal changes to 'thanks and links' view

vs

- enter email
- submit
- thanks modal

**Comment by jeffdomke** [comment]
@GinaAbrams @xanbots how much do you guys care about having the name field? I know we were collecting it before so we could reach out to folks. Critical? Don't care?

**Comment by GinaAbrams** [comment]
Don't care, personally

**Comment by xanbots** [comment]
Doesn't make a difference to me - feel free to remove

**Comment by jeffdomke** [comment]
OK, we could probably rethink the flow and CTA based on this one detail. Will save that for the next round of work. Sorry it doesn't make much sense now as is @aulneau
