### ISSUE TITLE
Change Copy 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#334]
First landing page: from The better your app, the more Bitcoin you earn. to->  The better your app, the more you earn.

We need to take out all references to Stacks as well i.e. this whole section: We currently pay in BTC for legal compliance. We plan to begin paying Stacks tokens early 2019 provided compliance with all applicable law.

**Comment by jeffdomke** [comment]
`We currently pay in BTC for legal compliance. We plan to begin paying Stacks tokens early 2019 provided compliance with all applicable law.` This is on the current page and I believe survived the last round of legal review.

**Comment by GinaAbrams** [comment]
Highly doubt that it got legal sign off. Do you recall when added? Pinging Freddie now about it.

**Comment by GinaAbrams** [comment]
Apparently, it did get legal sign off... we can keep if you guys think its helpful to devs

**Comment by GinaAbrams** [comment]
@aulneau @jeffdomke in the new version, looking at `Any app on App.co with Blockstack auth or storage can be ranked.` (right under the ranking blog posts.) Current phrasing might cause confusion where app.co apps feel they are registered. Something like below might be more clear: 

Any app on App.co with Blockstack auth or storage can be ranked. All you need to do is register.

What do you think?

**Comment by jeffdomke** [comment]
Any app with Blockstack auth or storage can register for App Mining.

**Comment by jeffdomke** [comment]
Arg. We have a classic bad ticket issue here now. Always split tickets. 

Moving latest comment to https://github.com/blockstack/app.co/issues/341 

Please restore the original text.
