### ISSUE TITLE
Major CTA match original design

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#343]
![Screen Shot 2018-12-07 at 5:34 PM](http://marker.screenshots.prod.s3.amazonaws.com/1f1d0a84227c4753a9f22d34772d48b3-1544204055069.png)

Box sizing, spacing, arrow, font size, text color, box corners. 

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-12-07%20at%2012.26.46%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-12-07%20at%2012.26.46%20PM.png)

**Comment by aulneau** [comment]
I added the arrow to the CTA button because I felt like it made it more clear that it was a button, versus an input/something else.

**Comment by aulneau** [comment]
Will adjust it to be closer. However the size will be fluid because it's dependent on the size of the page.

**Comment by jeffdomke** [comment]
Thx. I remember trying a variation with the arrow. I have some ideas for next iteration to make it more clicky and buttony.
