### ISSUE TITLE
Design bugs: Start app mining section

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#344]
![Screen Shot 2018-12-07 at 5:36 PM](http://marker.screenshots.prod.s3.amazonaws.com/55704c39aa8d4cb7b8a1da734a985a7a-1544204165171.png)

Match design on spacing, arrows, font sizing and font. 

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-12-07%20at%2012.28.35%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-12-07%20at%2012.28.35%20PM.png)

**Comment by aulneau** [comment]
I changed the type of the button as we're not really treating buttons with that typeface in any other places. It was a change for consistency. Will add the arrows. 

Also re: titles, I think we should either stick with sentence case (with punctuation) or title case. What do you think?

**Comment by jeffdomke** [comment]
Re button typeface: Other places like other web properties? We are on token website correct? 

I tend to default to sentence case as much as possible. With `App Mining` in particular I'm fine either way since we treat it as a proper noun. 

I was more referencing type size and the positioning relative to those icons.

**Comment by aulneau** [comment]
@jeffdomke what about `Get started with App Mining.`

**Comment by jeffdomke** [comment]
Buttons: We were but the sections got removed. And we are using it in the form fields. 

Changing the title to `Get started...`? sure its fine by me.
