### ISSUE TITLE
How much section: Design bugs. 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#345]
![Screen Shot 2018-12-07 at 5:39 PM](http://marker.screenshots.prod.s3.amazonaws.com/3f43a2cc6ec84d59a48111c69a591ec7-1544204371265.png)

Box sizing and radius, type sizes, fonts, arrow/button styles, icon size, sort indicator. 

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-12-07%20at%2012.28.56%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-12-07%20at%2012.28.56%20PM.png)

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/app.co/pull/335/commits/a52b867ff2544fd48446ac0929c418d6c416bdb0
