### ISSUE TITLE
Apps are ranked section: Design bugs

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#346]
![Screen Shot 2018-12-07 at 6:03 PM](http://marker.screenshots.prod.s3.amazonaws.com/09121f9c87444a50a942daf4f4388587-1544205816621.png)

Font sizing, box sizing, radius, colors

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202018-12-07%20at%2012.30.03%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202018-12-07%20at%2012.30.03%20PM.png)

**Comment by aulneau** [comment]
What is the rationale for the `Rankings are combined and payouts sent every 30 days.` to be a different size from all the other subtitle/body copy in other sections?

**Comment by jeffdomke** [comment]
Breakers = sure go for it. 

Text size = Originally the 30 day payout was included in the headline. Very important info, but the composition of the box and the headline is such that it looks like fine print that user should skip over even though it is pretty critical.
