### ISSUE TITLE
Change month to September for alpha run

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#351]
I think this would be more accurate as "Sep 2018" since that's what we say at https://app.co/mining/september-2018

<img width="419" alt="screen shot 2018-12-07 at 19 24 14" src="https://user-images.githubusercontent.com/28991/49665632-c17a9300-fa55-11e8-9a2a-432fb947cf38.png">

**Comment by aulneau** [comment]
I suppose it is debatable because it was announced in Oct? cc @GinaAbrams

**Comment by GinaAbrams** [comment]
Yeah, debatable. I'm ambivalent and if we've gone September in the past I think we can stick with that.
