### ISSUE TITLE
Add link to start kit confirmation screen

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#352]
It seems this highlighted text should link to the submission form:

<img width="679" alt="screen shot 2018-12-07 at 19 25 36" src="https://user-images.githubusercontent.com/28991/49665700-ed961400-fa55-11e8-965f-2cb08a394c11.png">

**Comment by aulneau** [comment]
It also seems that `App Mining Ready steps` should be a link too? cc @GinaAbrams

**Comment by GinaAbrams** [comment]
yeah, it probably should, with an outline of the collection for BTC address and W9 requirements. I'll throw together a paper doc with the initial copy for further review.

**Comment by GinaAbrams** [comment]
Copy would be along these lines [paper doc](https://paper.dropbox.com/doc/Untitled--ATQSbitVDiBhB_v17oqrVrHQAg-j5yT1hs5inwOHGnjkRPrW)

**Comment by aulneau** [comment]
@GinaAbrams where should this live (the info in the paper doc) cc @hstove

**Comment by aulneau** [comment]
Add the docs link for `App Mining Ready steps`
