### ISSUE TITLE
Misalignment of table 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#355]
![Screen Shot 2018-12-07 at 8:24 PM](http://marker.screenshots.prod.s3.amazonaws.com/ae71c775be3949f28eb3a964247e7a7b-1544214279832.png)
---
### More Info

**Source URL**: [https://app-co-staging-pr-335.herokuapp.com/mining](https://app-co-staging-pr-335.herokuapp.com/mining)

**Comment by aulneau** [comment]
Thanks for the issue. Will tackle this soon, but I'm planning on  hiding the lifetime amount until we have 2+ months worth of data.

Also what should the lifetime arrow do?
