### ISSUE TITLE
Copy bug: Typo

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#360]
![Screen Shot 2018-12-10 at 9:18 PM](http://marker.screenshots.prod.s3.amazonaws.com/a3c5e14ff62b46298f92aafa87f7f284-1544476715115.png)
---
### More Info

**Source URL**: [https://app-co-staging-pr-335.herokuapp.com/mining#](https://app-co-staging-pr-335.herokuapp.com/mining#)

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/app.co/pull/335/commits/e36ac6ea54533f0dcb7378b727a4870729447d00
