### ISSUE TITLE
App.co TOS: add link to app.co terms at bottom of page

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#368]
They are linked in registration flow currently but also need to be shown at the bottom of the page. https://app.co/terms . They should be listed as they are in the registration modal currently. 
<img width="450" alt="screen shot 2018-12-12 at 2 14 07 pm" src="https://user-images.githubusercontent.com/30627583/49892955-47148f00-fe18-11e8-8c77-62a55b0048c1.png">

**Comment by markmhx** [comment]
Is this what should have been addressed in this one? https://github.com/blockstack/app.co/issues/297
