### ISSUE TITLE
Clarify content inclusion for /mining/apps?

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#371]
The new app listings page for App Mining shows a mix of Blockstack apps that are fully "ready" and not ready, yet the header says "App Mining ready apps".

Should we clarify this a bit more? It seems that expectations are initially set as "you'll see just ready apps on this page" then further down the page you encounter "not ready" ones. 

I think we on the team know or assume that these "not ready" listings are simply apps on App.co categorized as Blockstack. But I don't think the average visitor will have a good idea for why these apps are also shown on this page.

If anything, they may think these "not ready" apps are those indicated by: "The list includes new apps which have not been ranked yet, but will be include in the next ranking." But that's not actually the case right, since those that are ready but haven't been ranked simply have "--" for lifetime earnings.

<img width="1222" alt="screen shot 2018-12-18 at 11 48 09" src="https://user-images.githubusercontent.com/28991/50149210-d4456100-02ba-11e9-8417-fa2c49965fc2.png">
<img width="1196" alt="screen shot 2018-12-18 at 11 48 14" src="https://user-images.githubusercontent.com/28991/50149211-d4456100-02ba-11e9-94a1-506b376f51f6.png">

**Comment by aulneau** [comment]
This is a status page for people to check their apps status in the context of app mining. This was a lot of Jeff's thinking. Maybe we can remove 'ready' from the title to solve some of the problems?

**Comment by aulneau** [comment]
I think this is something we should come back to, it shouldn't hold up a launch
