### ISSUE TITLE
Fix typo in start kit modal and add link to ready steps?

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#373]
We need a "k" in "Blockstack" here, and I believe we want to link the text "complete the App Mining Ready steps" to somewhere for that?

<img width="741" alt="screen shot 2018-12-18 at 11 50 05" src="https://user-images.githubusercontent.com/28991/50149395-6188b580-02bb-11e9-9578-b6553456f6eb.png">

**Comment by aulneau** [comment]
I don't know if there is actually a link to the 'app mining ready steps'. @moxiegirl do these exist in the docs?

**Comment by moxiegirl** [comment]
**Learn how with our zero to DApp tutorial**: https://docs.blockstack.org/develop/zero_to_dapp_1.html
**Register on App.co**:https://docs.blockstack.org/develop/mining_enroll.html

Suggested alternate:

**Have a user-ready Blockstack app?**

Complete the [enrollment steps and submit your paper work](https://docs.blockstack.org/develop/mining_enroll.html).
