### ISSUE TITLE
Link "all App Mining Ready apps"

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#374]
<img width="733" alt="screen shot 2018-12-18 at 11 53 02" src="https://user-images.githubusercontent.com/28991/50149496-a7457e00-02bb-11e9-9e2c-d37c7a6bf548.png">

**Comment by markmhx** [comment]
Also maybe all the text after the question mark should be simplified and make more imperative e.g. "View all App Mining ready apps"?

**Comment by moxiegirl** [comment]
@markmhx I think we are using the term enrolled to mean:

- Filled out the submission form
- Completed all the paperwork

That's what was reviewed and approved for the docs.
