### ISSUE TITLE
Auto update pioneer listings?

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#376]
It appears that the hero section is updated with the latest (December) results, but further down the page, the pioneers section still shows September results. Should that section also auto-update with the latest results? Or have we intentionally hard-wired September?

<img width="1222" alt="screen shot 2018-12-18 at 12 01 03" src="https://user-images.githubusercontent.com/28991/50149936-cd1f5280-02bc-11e9-9a95-16a5d0f366e9.png">

**Comment by aulneau** [comment]
This is intentional.

**Comment by aulneau** [comment]
Closing this because this section is meant to stay static and not update.
