### ISSUE TITLE
Provide different modal header for subscription CTA

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#377]
When I clicked the "Subscribe for Updates" button, I expected to see a more default looking email list prompt instead of the starter kit.

Is the intention to send people the kit here as well? Or do we want to provide a different prompt in the modal?

<img width="841" alt="screen shot 2018-12-18 at 12 03 50" src="https://user-images.githubusercontent.com/28991/50150048-27b8ae80-02bd-11e9-94b8-96e7f03c492a.png">

![Screen Shot 2019-01-29 at 18.58.27.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/d1d8d61a-56db-4756-a3b7-2d0adc21b1be)

![Screen Shot 2019-01-29 at 19.00.07.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/4ef9c64a-4a8b-4158-8741-43ecddffbcc9)

**Comment by aulneau** [comment]
The intention was I believe for it to be the same. Maybe we should change the button?

**Comment by aulneau** [comment]
This has been addressed with https://github.com/blockstack/app.co/commit/52c1e484eb2861d917c5c785a89a8befd55c52f3

**Comment by markmhx** [comment]
I've confirmed this change is live in production
