### ISSUE TITLE
Update links in "How do I submit my application for App Mining?" FAQ section

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#381]
The first doesn't go anywhere yet, and I believe the second should be changed to the location of these instructions on the docs site.

<img width="623" alt="screen shot 2018-12-18 at 12 21 16" src="https://user-images.githubusercontent.com/28991/50150847-84b56400-02bf-11e9-8dfd-cab0a73a1773.png">

**Comment by aulneau** [comment]
This is actually an issue for @moxiegirl in the docs.blockstack.org repo

**Comment by moxiegirl** [comment]
@aulneau Instructions exist and are here: https://docs.blockstack.org/develop/mining_enroll.html

**Comment by moxiegirl** [comment]
@aulneau Published.  I'll leave you to close this one your end at will.

**Comment by markmhx** [comment]
Thanks!
