### ISSUE TITLE
Allow URLs without protocol prefixes in app submission form

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#382]
'cause this is kinda annoying as a user:

<img width="809" alt="screen shot 2018-12-18 at 12 26 22" src="https://user-images.githubusercontent.com/28991/50151090-3359a480-02c0-11e9-8970-7c461dc663d8.png">

**Comment by aulneau** [comment]
I actually don't think we should allow this.

**Comment by markmhx** [comment]
I've taken this out of the App Mining project since I agree it wasn't necessary for launch. However, I would highly recommend that we make this change at some point. My presumption is that almost all users will attempt to submit these values without protocols and will find it frustrating to be required to add the protocol to three fields subsequently.
