### ISSUE TITLE
Turn label text into actual label elements in app submission form

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#384]
So that they're clickable, especially in this top item where I'd want to click on text (especially on mobile) to select a radio value.

<img width="374" alt="screen shot 2018-12-18 at 12 29 34" src="https://user-images.githubusercontent.com/28991/50151264-b0851980-02c0-11e9-8065-7022a4becb55.png">

**Comment by aulneau** [comment]
What browser are you using? It currently works like you describe for me.

**Comment by markmhx** [comment]
Chrome

**Comment by aulneau** [comment]
resolved with https://github.com/blockstack/app.co/commit/68ab8c0b8ef337d3bf2df91a355b40425e0932bf
