### ISSUE TITLE
Add copy to app submission form by image URL indicating support of only PNG or JPEG 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#390]
This is a temporary fix to indicate to applicants that SVG images do not work. cc @hstove

**Comment by aulneau** [comment]
SVG images should work, where are they not working?

**Comment by aulneau** [comment]
Ah I see. This is an svg that is being returned as plain text: https://appco.imgix.net/apps/1b1124d0-7bef-4a59-b7c0-6a29f985e961?format=auto&fit=clip&h=144&w=144

@hstove is there a way to pass along the content type? I feel like imgix def supports svg, and so i think the issue might be related to how we're saving the images and then processing them.

**Comment by aulneau** [comment]
https://support.imgix.com/hc/en-us/articles/360000977386-Can-I-render-SVG-files-with-imgix-
