### ISSUE TITLE
Add SVG image acceptance to our image proxy service 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#391]
I hope this is clear 😅

**Comment by cuevasm** [comment]
I would actually suggest we don't accept SVG (if this is related to logos for the app pages), reason being the images get fed into email and is not supported in inboxes so it shows as broken.

**Comment by aulneau** [comment]
We are using imgix which allows us to format the images after the fact as we wish. For example @cuevasm you can append `format=png` to the url and it will always be a png.

> Add SVG image acceptance to our image proxy service

I'm not sure what you mean exactly @GinaAbrams :) could you clarify?

**Comment by GinaAbrams** [comment]
Sure! Right now, SVG links are not being reflected on app.co/mining/apps (so their logos are not populating properly.) @hstove indicated today that we could potentially add SVG acceptance to the submission form if we indicate it as so on our proxy service? 🤔

**Comment by markmhx** [comment]
This issue will be resolved with https://github.com/blockstackpbc/app.co-api/issues/1
