### ISSUE TITLE
App Mining email design and copy improvements

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#403]
![Screen Shot 2019-01-08 at 12:11 AM](http://marker.screenshots.prod.s3.amazonaws.com/ff67cbc071d04a2e86596433d322ce1b-1546906287990.png)
---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202019-01-07%20at%206.50.15%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202019-01-07%20at%206.50.15%20PM.png)

**Comment by jeffdomke** [comment]
![iphone x](https://user-images.githubusercontent.com/767828/51394295-0e975d80-1b08-11e9-9c97-0955ecb9d2c9.png)

@cuevasm mocked this up in Figma quickly, just trying to reduce the repetitive text and statements as much as possible. Don't think we need the sections or graphics, just the updated logo and clear CTAs.

**Comment by markmhx** [comment]
@cuevasm Were you able to complete this issue as part of last sprint? If not, we should consider moving it to the sprint starting this week, assuming it fits into your workload for the new sprint.

**Comment by aulneau** [comment]
While working on design examples for the guidelines I implemented this email in a new way:

![app-mining-email](https://user-images.githubusercontent.com/11803153/51851818-4b263e80-22ea-11e9-80f5-a3f18e5196bb.png)

@jeffdomke lmk if you want us to go this direction?

**Comment by markmhx** [comment]
@cuevasm Jeff approved the above design from Thomas so we're good to go with the integration.

**Comment by cuevasm** [comment]
Implemented most feedback and updated the design. Can't wait for the brand kit you guys are cooking up, makes it a lot easier to make these things look great.

[app-mining-starter-kit-email (1).pdf](https://github.com/blockstack/app.co/files/2858272/app-mining-starter-kit-email.1.pdf)

**Comment by cuevasm** [comment]
Yep, been live for a couple weeks.
