### ISSUE TITLE
Add your app – type color and sizing. Type currently is hard to read

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#406]
![Screen Shot 2019-01-08 at 12:16 AM](http://marker.screenshots.prod.s3.amazonaws.com/899111b3f60442df9831c03e7823571c-1546906563080.png)
---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202019-01-07%20at%206.53.54%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202019-01-07%20at%206.53.54%20PM.png)

**Comment by jeffdomke** [comment]
The figma design isn't amazing, more of a wireframe really. But if the type sizes were the same, and the type color was the same, then the placeholder text and the fine print would be more legible. 

`Want to add a new cat...` should be the smaller text. 

`Blockstack authentication is required` hard to read text should be darker and/or larger. 

`IPFS` placeholder is hard to read needs to be darker text.

**Comment by aulneau** [comment]
> IPFS placeholder is hard to read needs to be darker text.

Do you want this change for all placeholders then?

> But if the type sizes were the same, and the type color was the same, then the placeholder text and the fine print would be more legible.

The figma was a wireframe, not at all a final ui imo, we should not integrate new random colors into things, eg black etc. I'll work on making a darker color for the placeholders and helpers, but I think the 'helper' messages should stay the same size, maybe increased very slightly.
