### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#41]
Figma designs: https://www.figma.com/file/SVFLfCU2cmkyCGcpjpmUVn/App.co-JD?node-id=970%3A0

TODO:

- [ ] navigation bar
- [ ] subscribe widget
- [ ] app list (table view)
- [ ] category list (grid view)
- [ ] featured section
- [ ] mobile nav (collapsed)
- [ ] app page

**Comment by markmhx** [comment]
@hstove How done are the designs here at the moment? 100% done? 53.25%?

And how much development has occurred so far?

**Comment by hstove** [comment]
Just started development on this redesign today, so that part rounds to zero.

In terms of how 'done' the designs are, I guess 100%, but its really just about getting to a place of consistent design (which I believe this accomplishes).

**Comment by markmhx** [comment]
We can discuss tomorrow during our call, of course, but my first thought it wondering whether it makes any sense to chunk this redesign down into separate issues / tickets for each of the checklist items you've listed. Or would that be too gnarly to do piecemeal?

Also, what would be your raw guess ETD for developing each or all of these items that make up the redesign?

**Comment by hstove** [comment]
My estimate for doing all of this is being finished between Monday and Wednesday of next week.

To the question of breaking up tickets - usually I prefer to keep tickets as small as possible, but in shippable components. In this case, we will only 'ship' this work in one push, because we won't push part of the redesign at once (although I'll keep a staging server updated with progress). Is that ok with you? I could be convinced otherwise.

**Comment by markmhx** [comment]
That's a fast estimate, so totally cool with keeping this as a single issue.

I think I was suspecting a few weeks of time so would have pushed for chunking more in that case.

**Comment by markmhx** [comment]
Also, I like the designs! Much better than the current ones and will provide a nice base for further iterations 💪🏻

**Comment by markmhx** [comment]
@hstove Are you pulling yourself off this issue entirely while @aulneau takes it over? Or are you both contributing?

**Comment by hstove** [comment]
Yes I think it's best to just let Thomas take over, so there aren't too many cooks in the kitchen with overlapping work, plus Thomas is likely faster than me on this stuff. I'm going to focus on #42, which will open up a few doors to new features.

**Comment by markmhx** [comment]
Cool, and @aulneau is your time estimate similar to @hstove's above?

**Comment by aulneau** [comment]
@markmhx yep! I should have a better idea tomorrow when I actually dig in but it should be the same

**Comment by markmhx** [comment]
I'm closing this issue in favor of a project to track the scope of the redesign: https://github.com/blockstack/app.co/projects/3
