### ISSUE TITLE
Pioneer apps – design bug

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#410]
![Screen Shot 2019-01-08 at 12:24 AM](http://marker.screenshots.prod.s3.amazonaws.com/803f146e29564cf2a0c957521c20dd04-1546907050362.png)

Imagine there should be 4 or 5 columns and the sizing of them possibly reduced. And centered. 

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/IMG_0438.PNG](file:///Users/jd/Desktop/IMG_0438.PNG)

**Comment by jeffdomke** [comment]
Just checked on iOS. See they are smaller, but there is still an odd space where a 4th column could reside within the page margin?

**Comment by aulneau** [comment]
If we do 4 columns, there will be a single item left at the end.

![Screen Shot 2019-01-09 at 10.06.35 AM.png](https://images.zenhubusercontent.com/5c0160f25cb43a45a18af171/b8bb60bb-bc6a-40ad-a2ff-cb67455c0c59)

**Comment by aulneau** [comment]
With css and not doing advanced custom math to get everything to layout manually, these are the results we can expect:

space-evenly

![Screen Shot 2019-01-09 at 10.07.56 AM.png](https://images.zenhubusercontent.com/5c0160f25cb43a45a18af171/b1a7a216-b93e-48d4-8658-2d5bb48b1e6f)

space-between (justified on both sides)

![Screen Shot 2019-01-09 at 10.09.01 AM.png](https://images.zenhubusercontent.com/5c0160f25cb43a45a18af171/ba016fd5-4bdb-4df4-b58e-2b9cecb9a39e)

**Comment by aulneau** [comment]
or with 4 columns and spaced-evenly

![Screen Shot 2019-01-09 at 10.09.57 AM.png](https://images.zenhubusercontent.com/5c0160f25cb43a45a18af171/d669d29f-7426-47a4-b247-cfeeaf1d4a22)

**Comment by jeffdomke** [comment]
Got it. Which one did you choose? 

Idea: Make them even smaller and achieve a 5th column. 

If that solution doesn't work, I'm fine with whatever you think is right. Don't like the 1 app in 5th row but the world won't end.
