### ISSUE TITLE
Nav bar – type, type color, button sizing

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#417]
![Screen Shot 2019-01-08 at 12:35 AM](http://marker.screenshots.prod.s3.amazonaws.com/e94062734fcc4482b6b084276e2c7614-1546907716545.png)

Remember we chatted about the countdown color change. 

---
### More Info

**Source URL**: [file:///Users/jd/Desktop/Screen%20Shot%202019-01-07%20at%206.19.51%20PM.png](file:///Users/jd/Desktop/Screen%20Shot%202019-01-07%20at%206.19.51%20PM.png)

**Comment by aulneau** [comment]
So we're using the same components throughout. Is there a reason you don't want `App Mining` treated the same in the header as it is in the hero? 

> Remember we chatted about the countdown color change.

Can you please give details on to how you want it to be different than what is currently in prod.

Also can you detail your lines, as they are not immediately clear as to what they are indicating.

**Comment by jeffdomke** [comment]
The button is super loud, I played around with the size of it so it doesn't dominate everything else in every panel, which it kind of does. So would prefer the smaller size button and smaller type size to reduce the "slaps you in the face" effect. 

Bit of the same comment on logo. Just want to minimize that stuff in the nav bar since it is always visible. I remember playing with the logo up there and decided to just make it all small text to keep things quiet. 

On figma text is white. On prod text is `color: rgb(194, 216, 229);` But we discussed making the `D``H` `M` text blue or reduced opacity due to a legibility issue.

**Comment by aulneau** [comment]
> But we discussed making the D``H M text blue or reduced opacity due to a legibility issue.

Yep that's why the text is a different color. I played around with a few options and landed on what you see currently. I reduced the colors of the time units to what you originally suggested, but felt it was too hard to easily grasp what it was. If you have something you'd prefer, can you mock it in figma?

Everything else sounds good, I'll reduce the text size of the button and change the logo

**Comment by jeffdomke** [comment]
Looking beautiful 👌
