### ISSUE TITLE
Add Blockstack ID to app reg submission form or docs site as part of the registration process 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#418]
This is for founders to communicate about their app in the democracy earth platform. Possible @aulneau @hstove @jeffdomke ? 🙏

**Comment by GinaAbrams** [comment]
@moxiegirl meant [here](https://docs.blockstack.org/develop/mining_enroll.html) but we may need to discuss first 🙏

**Comment by markmhx** [comment]
@GinaAbrams is this issue still relevant?
