### ISSUE TITLE
Collect metrics from Similar Web and show in app profile

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#42]
Metrics:

- page views
- time on page
- uniques
- others?

This is a precursor to #2

**Comment by markmhx** [comment]
@hstove Just a reminder here that it'd be great to have an updated description on this issue with exact info on what metrics we're collecting and how when you have the chance 💪🏻

**Comment by hstove** [comment]
Metrics we're collecting:

- Total visits
- Page views
- Bounce Rate
- Time on Site

These are available on a daily, monthly, and weekly basis, but due to a limitation that only lets you get up to last month's data, we'll probably just use monthly metrics.

**Comment by markmhx** [comment]
And Similar Web gives us just a simple average for "time on site" e.g. "2:02" and "bounce rate" e.g. "73%" for a given period aka the month for which we pull each time?

**Comment by hstove** [comment]
Yes thats correct.

**Comment by pstan26** [comment]
Quick Q: how gameable is this? If so, do we want to publicly disclose this
as a part of ranking?

**Comment by hstove** [comment]
It's gameable, but much much less gameable than simply using Twitter mentions. It's just as gameable as something like your "Alexa ranking", which I think would be easy for small apps, and hard for big apps. You'd have to spoof hundreds of thousands of unique visitors, which would not be easy.

And we'll definitely update the section of our FAQ page once we update our ranking algo to indicate that it's a composite ranking of different metrics, with specificity. Plus, it'll all be open source.

**Comment by pstan26** [comment]
Sweet!

**Comment by markmhx** [comment]
@aulneau I'm thinking you could take on the design for this issue next week while I'm away, whether or not @hstove has finished the metrics integration on the back-end completely or not.

Basically, for the "show in app profile" part of this issue, we want to display all of these data points on an app page / modal as available:

- Total visits last month
- Average page views per user
- Average bounce Rate
- Average time on Site
- Total tweets from past week

The obvious choice would be to redesign this part of the app profile in particular to accommodate that data:

<img width="708" alt="screen shot 2018-08-02 at 15 23 41" src="https://user-images.githubusercontent.com/28991/43586515-19f4d326-9668-11e8-9ee9-7df2fd383483.png">

I imagine there's a way to do that stylishly *and* informatively in an efficient at-a-glance kind of way.
