### ISSUE TITLE
Ensure that email address in addition to timestamp entered into spreadsheet upon start kit form submission

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#423]
@hstove following up from stand-up to investigate the blank fields with timestamps 🙏

**Comment by hstove** [comment]
I just fixed this. I'm assigning to @GinaAbrams to confirm.

**Comment by markmhx** [comment]
@GinaAbrams Have you been able to confirm that this works as intended? If so, let's close the issue out.
