### ISSUE TITLE
Need way to differentiate entries coming through app.co/submit

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#425]
Need solution for the problem of differentiating folks submitting on https://app.co/submit as folks that want to be entered into App Mining vs. just people submitting an app to app.co. Right now I'm not aware of a way for us to tell the difference between someone filling the form in on /submit as someone starting their app mining registration as instructed, OR simply hoping to submit an app to the app.co directory. (I realize that in both cases the app makes it to the app.co directory, however, the messaging to these two different groups is different I want to give the App Miners a certain email with next steps and that wouldn't make sense to just the regular person submitting an app).

One way I thought of (not tied to it at all), is a simple checkbox on the form where they could indicate if they are indeed here for App Mining.

![image](https://user-images.githubusercontent.com/6131188/50990070-f307d380-14c5-11e9-9fc5-af2e32cb074e.png)

**Comment by aulneau** [comment]
I think if we have a checkbox that states

```
[] I would like my app to be submitted for the App Mining program.
```

that it should only be visible if the app is a blockstack app.

But to a different point, do we want to allow any blockstack apps to _not be_ immediately added to the app mining program? cc @jeffdomke

**Comment by cuevasm** [comment]
Hank just explained to me that we're making the assumption that any app coming through this form that is marked as using Blockstack wants to be in app mining and we automatically treat that as a a submission. I'm not 100% sold on that generally, but it's fine for now and that will work for my purposes. I think you we can close this for now.
