### ISSUE TITLE
Add funnels tracking to App Mining

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#427]
Option: Mixpanel events
Option: URL routes on key interactions like the modal, and submit, so we can understand conversion

# App Mining page conversion through starter kit

This funnel has three entry points. Events needing instrumentation:

1. View App Mining landing page
2. Open start kit email form modal
3. Submit email form modal
4. Click to documentation link

# Clicks within "Get started with App Mining"

1. View App Mining landing page
2. Click on a click (specify which in tracking)

# Submits app form

1. View form
2. Failed to submit form
3. Succeeded at submitting form

**Comment by hstove** [comment]
We (were) tracking GA events for opening the modal and then registering it. We don't have that any more, since we just have the submission page. We can add events as we see fit to setup a modal.

**Comment by jeffdomke** [comment]
Ideally would be able to see funnel in URLs or events from clicks on CTA -> submits email –> clicks on Zero-to-dapp or registration form. 

Could be with mixpanel events, GA, or some other method.

**Comment by markmhx** [comment]
@aulneau @hstove  I've included this issue in the sprint starting today with your assignments. I'd recommend discussing between the two of you who should assume responsibility for it, given your respective workloads. Please let me know if neither of you can take it this sprint.
