### ISSUE TITLE
Fix links color on App Mining terms page

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#432]
Links are showing up in blue almost the same as the page background in both the header and footer.

https://app.co/mining/terms

<img width="1133" alt="screen shot 2019-01-15 at 17 28 11" src="https://user-images.githubusercontent.com/28991/51214135-0ca48300-18eb-11e9-92b4-5fdeb68f477c.png">
<img width="1079" alt="screen shot 2019-01-15 at 17 28 13" src="https://user-images.githubusercontent.com/28991/51214136-0ca48300-18eb-11e9-8fae-d55904606001.png">

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/app.co/commit/98a13924cfdb655a749a3a24ef57727675986638

**Comment by markmhx** [comment]
I've confirmed this is fixed in production
