### ISSUE TITLE
Add platform logos to platform list

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#44]
Add platform logos to the platform list module as shown here:

<img width="571" alt="screen shot 2018-07-27 at 16 06 30" src="https://user-images.githubusercontent.com/28991/43325485-0f1d479a-91b7-11e8-8062-f336fd1aab3d.png">

**Comment by markmhx** [comment]
Looks good except IPFS and ZeroNet logos aren't loading:

<img width="603" alt="screen shot 2018-07-30 at 13 45 06" src="https://user-images.githubusercontent.com/28991/43395545-c7ada90a-93fe-11e8-8509-9767b48ac699.png">
