### ISSUE TITLE
Finish table view

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#45]

**Comment by markmhx** [comment]
It appears that on narrower viewports that the various columns get crunched together:

<img width="459" alt="screen shot 2018-07-30 at 13 58 16" src="https://user-images.githubusercontent.com/28991/43396088-b4d715da-9400-11e8-8470-bec77cfd018b.png">

It would seem best to convert the table view to hide column headers and show just the first column with the app logo, name, description and numeric ranking similar to what we have on the homepage?

<img width="571" alt="screen shot 2018-07-30 at 13 58 24" src="https://user-images.githubusercontent.com/28991/43396122-d0d7fde4-9400-11e8-8a98-821130212011.png">
