### ISSUE TITLE
App Display: Git repo in the app listing 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#451]
Friedger suggested we add the git repo in the app listing or add a filter by open source in app.co

**Comment by friedger** [comment]
Currently, it is hidden behind the details screen.

**Comment by markmhx** [comment]
@friedger We discussed this a bit and think it'd be best to keep such links out of app listings. However, we'd love to make it possible to filter such views by open source and other criteria, so we've created an issue here to track that enhancement: https://github.com/blockstack/app.co/issues/458

Please let us know if you think that addresses the core need here you have in mind!
