### ISSUE TITLE
Can we rank Blockstack apps by the amount they have earned? 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#454]
Re: this list [popular Blockstack apps](https://app.co/blockstack
)
Would be awesome if it could be listed as here: [All Mining eligible apps](https://app.co/mining/apps)

Just starting the conversation to see if possible.

**Comment by markmhx** [comment]
Closing this one out in deference to broader score work tracked with https://github.com/blockstack/app.co/issues/21
