### ISSUE TITLE
Email validation hangs forever. 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#461]
![Screen Shot 2019-02-14 at 6:07 PM](http://marker.screenshots.prod.s3.amazonaws.com/9031284e8ce4452c91d14e3fe8cf4190-1550167647238.png)

Not sure what this thing does but it should timeout much faster and display some kind of helpful message. 

---
### More Info

**Source URL**: [https://app-co-staging-pr-453.herokuapp.com/mining](https://app-co-staging-pr-453.herokuapp.com/mining)

**Comment by markmhx** [comment]
Fails with "bob@bob.bob"

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/app.co/commit/ce745c81a3b04d06b58c77d9619d35a4617fd1b0
