### ISSUE TITLE
Update App Mining Apps List 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#464]
**Describe the bug**
The list of apps [here](https://app.co/mining/apps) seems to be populating with rejected apps. 

**Expected behavior**
The list should only display apps that are truly eligible for app mining rewards, no rejected or animal kingdom apps.

**Comment by hstove** [comment]
@GinaAbrams this should be fixed, can you review and close if so?

**Comment by GinaAbrams** [comment]
Indeed it is! Beautiful -- thanks @hstove!!
