### ISSUE TITLE
Fix color on FAQ so links are visible

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#468]
![image](https://user-images.githubusercontent.com/6131188/53220882-add5d600-361b-11e9-986f-f55511642979.png)

**Comment by GInxh** [comment]
@cuevasm Mitchell can you label this and assign someone, and assign it to an epic or a project? For example, is this something @aulneau or @jeffdomke would do? I am the only one triaging these, but I am not allowed to assign people as you made this for whatever reason/permissions. Please assign who would actually implement this, or to a related epic.

**Comment by cuevasm** [comment]
I can on this one but I don't think that should generally be an expectation. I don't think it's my place to assign people things especially when it's unclear to me who would be responsible for it. Like, maybe this one is @hstove? How do I really know? I think entering the issue should be enough especially given we want more and more non employee participation.

**Comment by cuevasm** [comment]
It's especially not my place to be putting it in projects and epics. Happy to learn otherwise, but this was a big no no on every other product team I've been on, it should be up to the product manager/engineer to allocate resources.

**Comment by hstove** [comment]
@GInxh I would agree with Mitchell that I'd rather Mitchell just create this issue and put it in `New Issues` unassigned (which it is by default). We triage issues in all of our main repositories every week or two.

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/app.co/commit/98a13924cfdb655a749a3a24ef57727675986638
