### ISSUE TITLE
Email links to direct mentions should load the post in the larger stream

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#469]
Currently the link takes you to a page that only displays the single mention. 

Would be super cool to take the user to the mention inside the context of mentions around it. Or, maybe load 20 before and 20 after. Context matters here and I assume showing more would make the likelihood of engagement higher/better. 

For example: https://staging.banter.pub/messages/8672b1744974-4040-bf8b-984fe907e1d8

**Comment by hstove** [comment]
Yes, it's immediately obvious that most mentions are 'replies', and you need a 'show replies' feature.

Showing adjacent messages is a decent short-term fix but still doesn't really work. We can do a dedicated 'reply' button, just like Twitter, that includes a mention as the start of the message. Then store the reply metadata in the model, so we can do threading-type-features. You could also get notified for replies even if they don't have an @ mention.

**Comment by jeffdomke** [comment]
Guess it depends on the future vision: 

- If Banter is a single wall everyone graffitis on, then before/after comments make sense (and are replies by nature) 
- If Banter becomes just like twitter, and each user has a distinct feed, meaning there is no canonical list of messages, then what you said make sense.

**Comment by hstove** [comment]
Well, it's highly likely that it will remain a 'global wall' for at least a long time. So I agree with your first point. It's pretty easy to fetch the posts adjacent to a specific one, and show those around it, maybe 'highlighting' the specific post the page is showing.

**Comment by hstove** [comment]
BTW, wrong repository. I guess I can't move an issue to outside the organization, so I created one here: https://github.com/blockstack-radiks/banter/issues/14
