### ISSUE TITLE
Fix FAQ page

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#47]

**Comment by markmhx** [comment]
Let's add the following styles to the `div` containing the page content:

## Desktop

<img width="1698" alt="screen shot 2018-08-01 at 12 31 10" src="https://user-images.githubusercontent.com/28991/43516824-fe105950-9586-11e8-91f0-576b9582cfbd.png">

## Mobile

<img width="1707" alt="screen shot 2018-08-01 at 12 31 44" src="https://user-images.githubusercontent.com/28991/43516832-014a25d8-9587-11e8-81a0-7d2afd4c0b3d.png">

**Comment by markmhx** [comment]
I'm moving this back into "Needs development" since it doesn't appear done properly.

**Comment by markmhx** [comment]
I've moved this back to development since I don't see the change on staging still.
