### ISSUE TITLE
App.co Homepage Issue

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#473]
Under the Blockstack Apps tab on the app.co homepage, there is a prompt to `view all`. The button is not working on chrome. Havent tested other platforms.

**Comment by markmhx** [comment]
I've recreated in both Chrome and Firefox; not working for me in either.

**Comment by hstove** [comment]
Hey @markmhx or @GinaAbrams , can you confirm this is fixed?

**Comment by GinaAbrams** [comment]
Working! Thanks @hstove !
