### ISSUE TITLE
Update Listing order of Blockstack apps on app.co 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#474]
Currently, we're displaying apps on [https://app.co/blockstack](https://app.co/blockstack) by tweets per week. 

Would like for these apps to be listed as they are in accordance to their rank as on this page: [app mining](https://app.co/mining/apps). 

This would not include payment amounts, just the order of the apps. Think it would be helpful to folks who want to check out the top apps, and we're also using this methodology on the homepage.

**Comment by hstove** [comment]
It sounded like there is some urgency to this, yeah? Any kind of timeline?

**Comment by GinaAbrams** [comment]
Hey @hstove will update here today.

**Comment by GinaAbrams** [comment]
Sorry -- I dont have an update here yet!

**Comment by markmhx** [comment]
@hstove can you tackle this issue during the sprint starting today?

**Comment by GinaAbrams** [comment]
@hstove this can be closed, correct? 🙏
