### ISSUE TITLE
Smart link that always resolves to the latest App Mining results

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#477]
Number of useful cases for marketing and on web properties. The link should be something like app.co/mining/results and it would always resolve to the most current month's page, such as https://app.co/mining/march-2019

**Comment by markmhx** [comment]
@cuevasm would it work if we set up a URL that took the visitor directly to this section on the App Mining landing page, which will always show the latest results?

![Screen Shot 2019-03-25 at 18.48.07.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/2ed775c6-4226-4a07-9f40-5ef5b2b86146)

**Comment by cuevasm** [comment]
Not really, I prefer the page with the full results, app reviewers on the
side, etc. + It makes it easy to compare growth of traffic to the results
page each month and that's primarily what we want to be sharing.

**Comment by markmhx** [comment]
Makes sense, @aulneau that sound good to you? That we just create a route that always redirects to the latest dedicated monthly page?

**Comment by markmhx** [comment]
This has been resolved
