### ISSUE TITLE
PH: Change ranking input to number of upvotes this month

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#480]
Idea is to eliminate apps having a long term advantage based on a one time launch. And if apps want to find ways to boost upvotes post-launch that is fine.

**Comment by jeffdomke** [comment]
Issue moved to [blockstack/app-mining #78](https://github.com/blockstack/app-mining/issues/78) via [**ZenHub**](https://www.zenhub.com/)

**Comment by friedger** [comment]
@jeffdomke Do you have insight about how many upvotes a product gets one, two, three month after hunting?

I see PH as a score how successful the launch was. This encourage app publishers to prepare the launch as good as possible. Is it fair to products that have already launched? My understanding is that you can relaunch as well.
