### ISSUE TITLE
Ensure that app.co/mining/apps data is not cached

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#484]
For example, the Recall app icon has been updated in the admin panel but remains outdated:

![Screen Shot 2019-03-25 at 18.44.55.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/604d7185-1dc1-42d2-895f-fe88c842855b)

@hstove is this something you can help resolve during the sprint starting today?

**Comment by GinaAbrams** [comment]
@markmhx are we able to assign someone on this? It would really help to communicate to Miners that their apps are ready for inclusion in the April rankings.

**Comment by markmhx** [comment]
Sorry we didn't assign this issue for this sprint on Monday, since it seemed like everyone had enough on their plate. But @hstove @aulneau, any chance you _do_ have room for a bit more and want to take this? Otherwise we may need to assign to next sprint.

**Comment by hstove** [comment]
We got a fix out on Friday 👍
