### ISSUE TITLE
Fix privacy policy and Terms

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#486]
4.3 should refer to 4.C. Looks like there was a formatting problem where the numbers got switched to letters. Need to fix to make consistent one way or another.
![image](https://user-images.githubusercontent.com/6131188/55382474-96bbbb00-54da-11e9-9d8d-20d471013306.png)

Link doesn't work, should be just /privacy:
![image](https://user-images.githubusercontent.com/6131188/55382504-a804c780-54da-11e9-976d-1be14768268e.png)

Couldn't duplicate, but reported that it won't load when tried to access directly - If you click on "privacy policy" at the bottom of https://app.co/, it should load. There is a bug where it doesn't load if you try to access it directly.

cc @fjl4 in case he has preferences on any of this.

**Comment by hstove** [comment]
Thanks @cuevasm . I just pushed #488, which addresses these issues. The error about not being able to load /privacy directly was fixed last week.
