### ISSUE TITLE
Redo 'submit' page

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#49]

**Comment by markmhx** [comment]
Let's apply the same general page styles to this page as the FAQ page, re: https://github.com/blockstack/app.co/issues/47

And let's give the form element itself a maximum width of 512px and let it float in the center of the page within the wider div with a white background

**Comment by markmhx** [comment]
I'm moving this back into "Needs development" since the padding part of it doesn't appear done properly.

**Comment by hstove** [comment]
I don't understand. It seems to be exactly what your last comment is. It's not on the left like the FAQ page, but you said to center it?

**Comment by aulneau** [comment]
Not to make this too complicated, but I think a modal might serve this content better.

**Comment by markmhx** [comment]
By "padding part", I'm referring to the need to change the content container's padding to 64px on desktop and 32px on mobile per https://github.com/blockstack/app.co/issues/47#issuecomment-409530131.

For example on desktop, it currently has padding of 24px:

<img width="1383" alt="screen shot 2018-08-22 at 10 10 08" src="https://user-images.githubusercontent.com/28991/44451324-c07f3c00-a5f3-11e8-8473-80ba5f363d45.png">

But it should look like this with 64px:

<img width="1407" alt="screen shot 2018-08-22 at 10 10 29" src="https://user-images.githubusercontent.com/28991/44451353-d7be2980-a5f3-11e8-86cd-d22535399b45.png">
