### ISSUE TITLE
App registration: Add section for type of app for TryMyUI testing

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#490]
If possible, would like to get this rolling re: "Web, android, ios, other" given it is required for TryMyUI tests and currently manual work.

**Comment by markmhx** [comment]
When we tackle this, we probably want to solicit multiple URLs per app per platform

**Comment by markmhx** [comment]
I'm closing this issue out in favor of https://github.com/blockstack/app.co/issues/666
