### ISSUE TITLE
Fix "Invalid Date" on App Mining page for Safari

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#492]
Reported by @larrysalibra 

![IMG_E4A1A8C53BD8-1](https://user-images.githubusercontent.com/28991/56146981-9d046980-5fa7-11e9-837d-06d6035b1bcb.jpeg)

**Comment by timstackblock** [comment]
This is resolved

<img width="1243" alt="Screen Shot 2019-06-06 at 3 40 51 PM" src="https://user-images.githubusercontent.com/49165468/59061492-a5737500-8871-11e9-91e9-ab705b59adfc.png">
