### ISSUE TITLE
App Mining Not Drawing from Approved FAQ source allFAQs.json

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#493]
With the latest filing, we've added a new FAQ source that is the central location for all the FAQs. blockstack.org and statckstoken.com are using the new source. App mining is still using the old one, we need to update App Mining to use the new source.

**Comment by markmhx** [comment]
@hstove Does this issue entail simply changing the API URL from which FAQ data is drawn?

**Comment by hstove** [comment]
Not quite - I think the FAQ is stored in app.co's codebase right now. We'd have to rewrite how that data is fetched and only select the subset of FAQ we want for app mining.
