### ISSUE TITLE
Don't send sample apps through app mining flow

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#495]
Right now, if you submit a sample app (from zero-to-dapp), they are sent through the app mining flow. This shouldn't happen.

**Comment by moxiegirl** [comment]
@hstove Can you elaborate on what you mean here? The intention was that the user experience "what it is like to submit an app to app.co" so going through the flow is normal. The fact that they use the category Sample Blockstack Application triggers me to trap their email and they get a tshirt. All this is as designed.

**Comment by hstove** [comment]
Yep, this will all stay. Currently, they get an email about 'next steps for app mining'. Obviously we don't want that to happen for sample apps.

**Comment by markmhx** [comment]
@hstove What changes did you make ultimately for this issue and should we close it?

**Comment by hstove** [comment]
I made a change on the API server, which handles the logic here. Good to close!
