### ISSUE TITLE
App mining page very slow

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/app.co#497]
The app mining page loads very slowly here in singapore.

The time to first byte is over 7 seconds.

<img width="1309" alt="Screen Shot 2019-04-30 at 4 03 49 PM" src="https://user-images.githubusercontent.com/597182/56948109-b558b480-6b61-11e9-8b11-e73ab67bed32.png">

Other blockstack properties load very quickly:

```
Vanquish:~ larry$ curl -w "@curl-format.txt" -o /dev/null -s https://app.co/mining
  time_namelookup:  0.005130
       time_connect:  0.224883
    time_appconnect:  0.283406
   time_pretransfer:  0.283590
      time_redirect:  0.000000
 time_starttransfer:  8.036549
                    ----------
         time_total:  9.216508
Vanquish:~ larry$ curl -w "@curl-format.txt" -o /dev/null -s https://blockstack.org
  time_namelookup:  0.005158
       time_connect:  0.103092
    time_appconnect:  0.151597
   time_pretransfer:  0.151797
      time_redirect:  0.000000
 time_starttransfer:  0.170862
                    ----------
         time_total:  0.279942
Vanquish:~ larry$ curl -w "@curl-format.txt" -o /dev/null -s https://stackstoken.com
  time_namelookup:  0.259084
       time_connect:  0.267473
    time_appconnect:  0.342442
   time_pretransfer:  0.342652
      time_redirect:  0.000000
 time_starttransfer:  1.248856
                    ----------
         time_total:  1.281136
```

This problem appears from loading the page in the USA as well: 

https://www.webpagetest.org/result/190430_2G_e24729d4d6fabb66b2afabd182908d94/

<img width="1015" alt="Screen Shot 2019-04-30 at 4 08 07 PM" src="https://user-images.githubusercontent.com/597182/56948259-2730fe00-6b62-11e9-8bf2-77dc07eeef11.png">

**Comment by larrysalibra** [comment]
Tried to load this page during a presentation and it showed “internal server error”

**Comment by larrysalibra** [comment]
In New York now and seeing the same slow loading issues.

**Comment by markmhx** [comment]
@larrysalibra Mind testing this again? @hstove made some speed improvements to App.co recently that may have helped here.

**Comment by larrysalibra** [comment]
@markmhx it seems a lot faster! great work @hstove ! Thanks for taking care of this!
