### ISSUE TITLE
Update: Update NoteRiot Icons

### ISSUE THREAD

**Issue by dantrevino** [blockstack/app.co#509]
@hstove 

Following up on https://github.com/blockstack/blockstack-browser/pull/1920

**Is your feature request related to a problem? Please describe.**
Update NoteRiot application Icons

**Describe the solution you'd like**
Replace existing icon(s) with the icons found here:
https://note.riot.ai/static/img/icons/app-icon-noteriot-256x256.png
https://note.riot.ai/static/img/icons/app-icon-noteriot-512x512.png

**Describe alternatives you've considered**

**Additional context**

**Comment by hstove** [comment]
All updated :+1:
