### ISSUE TITLE
Maker portal - esign using embedded view

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#522]
This also requires backend logic to get data from Eversign once the signature is complete. The user should see that we've received their e-sign.

**Comment by hstove** [comment]
This is ready for QA and testing. Here is the general flow:

1. Go to the 'document signing' portion of the maker portal
2. Submit your name and email. This is required before making the document to be signed
3. You should see the embedded e-sign iframe.
4. Submit some details. You only are required to sign it at the end. I haven't fully configured all of the fields in Eversign yet, but we can do that later.
5. After you submit, the app should immediately get a webhook from Eversign. If you refresh the page, and go back to the 'document signing' tab, you should see a message that says you've successfully submitted your docs.

**Comment by markmhx** [comment]
If I enter an invalid email address, the form refreshes (retaining the entered values) but does not redirect to the embedded e-sign iframe. Perhaps it's not critical, but we may want to add some sort of input-based email validation so the user knows why the submission didn't work?

**Comment by markmhx** [comment]
I was able to complete the QA testing steps by submitting a valid email address for app Zethr. @timstackblock can you test the same with a different app on staging?

**Comment by markmhx** [comment]
Also, I see that the "SEC terms accepted" checkbox on the admin page for the app seems to toggle "on" upon completion of these steps. Should there also be an admin view of the actual document that was signed?

**Comment by markmhx** [comment]
If I toggle this box off and try to visit "Document Signing" again, I see the following error:

<img width="1421" alt="Screen Shot 2019-06-17 at 15 43 13" src="https://user-images.githubusercontent.com/28991/59608909-a9778080-9116-11e9-9967-2b370b81311b.png">

Perhaps this checkbox should be disabled? Or is there a scenario in which admins can uncheck the box and have the user re-sign?

**Comment by markmhx** [comment]
I guess I'm not sure we need to take action on any of the above concerns given the sprint's urgency and our longer term needs. Are we expecting to maintain and improve this portal over the long-term, or is it a temporary stopgap?

**Comment by timstackblock** [comment]
@hstove for some reason when I restore account tjrwells.id.blockstack it opens another account see a video of the issue here https://screencast-o-matic.com/watch/cq1bYtTGIX 

This is the account you set with the admin privileges

please set the admin privileges on twellsjr.id.blockstack I cannot test this without admin privileges

**Comment by timstackblock** [comment]
I was able to complete this with graphite

![Screen Shot 2019-06-17 at 4.56.06 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/6e2f5541-7576-4a25-bedc-57a6dfd8fb4e)

**Comment by timstackblock** [comment]
need admin privileges for further testing on twellsjr.id.blockstack

**Comment by timstackblock** [comment]
I will retest with the auth token after this is resolved
https://github.com/blockstack/app.co/issues/536

**Comment by markmhx** [comment]
@timstackblock I believe this can be tested again

**Comment by timstackblock** [comment]
This works closing this ticket
