### ISSUE TITLE
Maker portal - embedded KYC flow

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#523]
User should be able to go through the embedded KYC flow. Our backend will receive their webhook and record the status of the KYC process. We will display the KYC status to the end user.

Question - if KYC fails, can they go again? This actually opens up a bad spot where a user could go through all of our verifications, if we didn't limit it.

**Comment by hstove** [comment]
QA instructions:

1. In maker page, go to 'Identity Verification' page
2. Click 'start'
3. Use embedded iframe to go through identity verification flow
4. Once it's done, wait a few minutes. It takes time for their automation to process the ID. It usually takes less than 3 minutes
5. Go to the admin page for this app
6. In the 'App Mining' section, see `Is KYC Verified: true`

Notes:

- Each verification costs us $3. There is no staging environment for them, and we have a limited quota. Try to be mindful of this. Don't QA their flow by inputting invalid pictures on purpose.
- We have no flow for notifying the user if the verification is rejected yet. Need to figure out how we want to do that on the product side.

**Comment by timstackblock** [comment]
QA blocked by this bug https://github.com/blockstack/app.co/issues/536

**Comment by markmhx** [comment]
@timstackblock I believe this can be tested again

**Comment by timstackblock** [comment]
![Screen Shot 2019-06-25 at 9.49.26 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/d541d2f9-9f9a-4c8c-8c3c-fb507a3b7182)

**Comment by timstackblock** [comment]
This works as expected
