### ISSUE TITLE
Adjust widths of category and platform cells

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#53]
Each sections should go full-width. When you click 'view all', it expands down to show all. On mobile, it should be 1 column wide, otherwise 5 columns.

**Comment by markmhx** [comment]
Does this correspond to your understanding of how we'd resize these widths from the meeting yesterday?

## Desktop

<img width="1189" alt="screen shot 2018-07-27 at 16 16 14" src="https://user-images.githubusercontent.com/28991/43326234-997125fa-91b8-11e8-8329-a21d8c14a572.png">

## Mobile

<img width="424" alt="screen shot 2018-07-27 at 16 16 49" src="https://user-images.githubusercontent.com/28991/43326237-9ba7ff60-91b8-11e8-8150-806eeb245549.png">
