### ISSUE TITLE
[Privacy Policy] Update Privacy Policy with Two New Paragraphs

### ISSUE THREAD

**Issue by fjl4** [blockstack/app.co#530]
Update the privacy policy at https://app.co/privacy with the two new paragraphs highlighted here: https://paper.dropbox.com/doc/Blockstack-Privacy-Policy--AfNaaMFqklUtunpE2j1cPWMHAQ-DvoEnYqpALpsbHHYjGqFR.

**Comment by markmhx** [comment]
Is this issue perhaps best assigned to @hstove since he's currently in the code most actively?

And @fjl4 is this change urgent?

**Comment by fjl4** [comment]
Within the next couple of days would be great.

**Comment by hstove** [comment]
Hey - I forgot to update this ticket. Thomas actually made this fix and we deployed it on Friday.
