### ISSUE TITLE
Signing into staging with the admin app does not work on safari

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#531]
Go to this link in safari

https://app-co-staging-pr-519.herokuapp.com/admin

Click the option to sign in with blockstack and you will get the error below

![Screen Shot 2019-06-17 at 3.45.29 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/5b0bb700-adcc-44a0-be91-4ea1eee55bc5)

![Screen Shot 2019-06-17 at 3.45.21 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/e3ac68e1-0145-48f4-8ecf-cc92bb4d98be)

**Comment by hstove** [comment]
Thanks. We'll want to deal with this when we introduce Blockstack auth for app developers. Until then, I think this is low priority, since the admin view is only for internal team members.

**Comment by timstackblock** [comment]
@hstove for some reason when I restore account tjrwells.id.blockstack it opens another account see a video of the issue here https://screencast-o-matic.com/watch/cq1bYtTGIX 

This is the account you set with the admin privileges

please set the admin privileges on twellsjr.id.blockstack

**Comment by markmhx** [comment]
@timstackblock Does this work for you now?

**Comment by timstackblock** [comment]
This is resolved
