### ISSUE TITLE
The green sign-in with blockstack button doesn't work in firefox

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#532]
VIDEO OF THE BUG
http://somup.com/cq1bqsnMK3

In a FIREFOX browser go to https://app-co-staging-pr-519.herokuapp.com/admin

You will see a green button that says sign-in with blockstack try to click it and it will NOT work

![Screen Shot 2019-06-17 at 3.55.09 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/4b2f7c1f-170d-4a92-9ed6-6960219614bb)

**Comment by markmhx** [comment]
@timstackblock Does this work for you now?

**Comment by timstackblock** [comment]
This works now
