### ISSUE TITLE
Cant login as an admin I get an infinite loop that keeps bringing me back to sign-in

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#536]
VIDEO OF THE ISSUE: http://somup.com/cq1F0wnLxC

Go to https://app-co-staging-pr-519.herokuapp.com/admin

Click the green "sign in with blockstack" button

You will be taken to the Blockstack browser where you will be logged in

Once your logged in blockstack browser will take you back to app.co but you will go right back to the login page. I cannot access the admin panel or test any admin functions because I am not being signed in.

![Screen Shot 2019-06-18 at 7.31.28 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/44d0ffec-2c31-4d46-ac57-354e2e223d8d)

**Comment by markmhx** [comment]
This appears to be resolved now that I'm unable to recreate this problem on either my iMac or Laptop in Chrome or Firefox. @timstackblock can you check as well?

**Comment by timstackblock** [comment]
This is fixed, works now in all browsers we can close this issue
