### ISSUE TITLE
Add guidance to payment details screen

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#538]
## Existing design

<img width="705" alt="Screen Shot 2019-06-21 at 16 08 09" src="https://user-images.githubusercontent.com/28991/59928320-c5dd2b00-943e-11e9-83b5-6b5e997286f5.png">

## Suggested changes

Add the following content above the Payment Details form of the Maker Portal to help clarify its purpose:

> Please provide the Bitcoin and Stacks addresses we should use to send you App Mining rewards.
> 
> Rewards will be paid out with Bitcoin until App Mining transitions to paying out with Stacks. You will not be eligible to receive rewards for any App Mining cycle if we don't have the relevant address on file given our preferred payment method at that time.

**Comment by markmhx** [comment]
@moxiegirl @jeffdomke Mind providing your feedback on this copy suggestion?

**Comment by jeffdomke** [comment]
Something like: 

> Please provide the Bitcoin and Stacks addresses that will automatically receive your App Mining payments each month. The easiest way to generate a Stacks address is via the official Stacks wallet made by Blockstack PBC. 

> Your app is not eligible for App Mining unless we have valid payment addresses on file. 

Link to: https://wallet.blockstack.org/

**Comment by moxiegirl** [comment]
@jeffdomke yours implies we are accepting multiple addresses and Stacks should be first. 

> Presently, App Mining payments are made to a Bitcoin (BTC) address. In the future, payments will be made to a Stacks (STX) address. Your app cannot participate in App Mining without Blockstack having *both* address types on file.

> Please provide a BTC and a STX address. For information on obtaining a STX address, see the [Stacks wallet documentation](https://docs.blockstack.org/org/wallet-use.html#receive-stacks)

And I'd like them direct to the receive...they can back out to get the wallet rather than drill down to how to get an address.

**Comment by markmhx** [comment]
When we go live with the Maker Portal in general, we will have begun paying out in both BTC and STX. As such, I don't believe we can say "Presently, App Mining payments are made to a Bitcoin (BTC) address" since we'll be paying in STX as well.

Perhaps the following version is more accurate (changes in bold):

> Presently, App Mining payments are made to **both a Bitcoin (BTC) address and a Stacks (STX) address**. In the future, payments will be made **only** to a Stacks (STX) address. Your app cannot participate in App Mining without Blockstack having *both* address types on file.
> 
> Please provide a BTC and a STX address. For information on obtaining a STX address, see the [Stacks wallet documentation](https://docs.blockstack.org/org/wallet-use.html#receive-stacks)

**Comment by markmhx** [comment]
Let's update the link in this description to either of these places so the user has an immediately apparent way to download the wallet:

- https://docs.blockstack.org/org/wallet-install.html
- https://wallet.blockstack.org

**Comment by markmhx** [comment]
The latest on staging is mostly correct, but since we're linking to https://wallet.blockstack.org, we should actually say "To obtain a STX address, download the Stacks Wallet" at the very end. Otherwise, it doesn't make sense to mention documentation and link to the wallet website.

<img width="882" alt="Screen Shot 2019-07-02 at 14 05 34" src="https://user-images.githubusercontent.com/28991/60511578-9ba72b00-9cd2-11e9-8ca2-80de26d8e058.png">

**Comment by markmhx** [comment]
Looks good
