### ISSUE TITLE
Modify description and button label on identity verification screen

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#539]
## Existing design

<img width="748" alt="Screen Shot 2019-06-21 at 16 09 23" src="https://user-images.githubusercontent.com/28991/59928460-13599800-943f-11e9-93fa-e1462a45336c.png">

## Suggested changes

Description should change to:

> We must verify your identity before considering you eligible to participate in App Mining.
> 
> Once initiating this process, you will have 60 days to complete it.

Button should change to "Begin verification"

**Comment by markmhx** [comment]
@moxiegirl @jeffdomke Mind providing your feedback on this copy suggestion?

**Comment by moxiegirl** [comment]
@markmhx sure. Is there reason we need to expose this term KYC at this level. It just adds a layer of tech speak when "identity verification" is pretty much useful. IF we need to use KYC:

![image](https://user-images.githubusercontent.com/1347209/59932038-2a769680-93fb-11e9-8af5-19675fd3a5bd.png)

If we dont' need that KYC terms for some reason, I'd go with a less sophisticated vocabularly 

![image](https://user-images.githubusercontent.com/1347209/59932397-e8018980-93fb-11e9-913e-9bf2f3951676.png)

**Comment by markmhx** [comment]
I agree we don't need to mention KYC.

Note though that the image included here is the existing screenshot, not the suggested changes. I've updated the suggested changes in the top description comment by removing any mention of KYC. Can you take a look at that new version?

**Comment by jeffdomke** [comment]
I agree KYC is cryptic. I also think the "why" here is relevant. So far in the process someone could remain anonymous, we need to reinforce why this is good for them and why they should put in effort to clear this hurdle. Suggest something like: 

> We need to confirm your identity before you can participate in App Mining. 

> We are ready to pay you Bitcoin and Stacks tokens for building a great Blockstack app, but we also need to comply with all applicable laws. We promise to keep your personal safe and private. 

> You have 60 days from today to complete this process.

**Comment by moxiegirl** [comment]
For some reason, the "promise to pay" sounds coercive and somewhat...shady...in this context. I'd go with something more direct.

> To comply with US laws, Blockstack must confirm your identity before you can participate in App Mining.  Your personal data is only shared with the [necessary legal authorities]().

> You have 60 days from today to complete this process.

**Comment by fjl4** [comment]
No need to say KYC. ID verification is good.

Is the 60-day time limit needed? If they don't complete KYC, then they can't get paid in Stacks, so it's really on them.

**Comment by hstove** [comment]
The 60 days is just a technical limitation of our KYC platform. You have to initiate a verification and they only last for 60 days

**Comment by markmhx** [comment]
The changes on staging look good to me. For reference, here's what's been integrated:

> We need to confirm your identity before you can participate in App Mining.
> 
> We are ready to pay you Bitcoin and Stacks tokens for building a great Blockstack app, but we also need to comply with all applicable laws.
> 
> You have 60 days from today to complete this process.

**Comment by timstackblock** [comment]
Changes look good, the" begin verification" button doesn't work but I think this ticket is just a change in the description.

@hstove @markmhx should this button be functional now or is this an upcoming change?

![Screen Shot 2019-06-25 at 9.26.42 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/f9705c11-3dae-446a-a3f4-d983137c5d23)

**Comment by timstackblock** [comment]
Igno
