### ISSUE TITLE
Modify description and button label on document signing screen

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#540]
## Existing design for before submission

<img width="744" alt="Screen Shot 2019-06-21 at 16 15 06" src="https://user-images.githubusercontent.com/28991/59928766-bf9b7e80-943f-11e9-9739-69fb2d1b3aaf.png">

## Suggested changes for before submission

Description should change to:

> You must sign our participation agreement to become eligible to participate in App Mining.
> 
> Provide your name and email address below to start the signing process.

Button should change to "Start signing process"

## Existing design for after submission

<img width="928" alt="Screen Shot 2019-06-21 at 16 16 39" src="https://user-images.githubusercontent.com/28991/59928887-f70a2b00-943f-11e9-869b-1b4ff823ebf4.png">

## Suggested changes for after submission

Then once the user has finished the process, change the description to:

> Thanks! You've successfully signed our participation agreement.

**Comment by markmhx** [comment]
@moxiegirl @jeffdomke Mind providing your feedback on this copy suggestion?

**Comment by moxiegirl** [comment]
@markmhx it would make sense to prepopulate the fields from the submission.  It would make sense to have confirmation at some point that these are were entered correctly  --- legal document and all.

![image](https://user-images.githubusercontent.com/1347209/59938874-16d32c00-940b-11e9-8537-2f9d6ec658f7.png)

**Comment by markmhx** [comment]
@hstove is pre-population something easy enough to wire up quickly?

**Comment by jeffdomke** [comment]
I'm good 👌
