### ISSUE TITLE
Fix navigation shrinking for Maker Portal

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#541]
When toggling the "Identity Verification" tab, the left-hand navigation column shrinks. It should stay the same width as on other tabs, keeping all tab label text on one line:

<img width="843" alt="Screen Shot 2019-06-21 at 16 18 48" src="https://user-images.githubusercontent.com/28991/59929056-510af080-9440-11e9-8d78-a9655b64c394.png">
<img width="840" alt="Screen Shot 2019-06-21 at 16 18 50" src="https://user-images.githubusercontent.com/28991/59929057-510af080-9440-11e9-8b5b-945080b83c01.png">

**Comment by markmhx** [comment]
Looks good to me 👍🏻

**Comment by timstackblock** [comment]
This works closing this issue
