### ISSUE TITLE
Maker Portal: Add validation to the STX and bitcoin fields

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#543]

**Comment by markmhx** [comment]
Do you have in mind that we simply require both fields for submission? Or that we validate the input somehow?

I'm not sure what regex pattern ought to match either type of address – basically any alphanumerical string? Of a certain max length?

@hstove thoughts?

We may want to let the user submit only one address – or remove previously submitted addresses – in case they want to manage their addresses in contexts in which both are not available to them. In other words, we may not want to make these required fields.

**Comment by markmhx** [comment]
@hstove Do you have guidance on how or whether we can implement this?

**Comment by markmhx** [comment]
Nevermind, I see you've integrated validation:

<img width="554" alt="Screen Shot 2019-07-02 at 14 07 19" src="https://user-images.githubusercontent.com/28991/60511621-baa5bd00-9cd2-11e9-893d-fb2809e23367.png">
