### ISSUE TITLE
Maker Portal: Add placeholder text to the STX and bitcoin fields

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#544]
Would be nice reassurance to know the address you're pasting in there looks like a valid STX address. It also might confuse people. @markmhx thoughts from wallet land?

**Comment by markmhx** [comment]
In the Stacks Wallet, we appear to use address placeholders that don't show example STX addresses but rather just solicit the value with a phrase, e.g.

![Screen Shot 2019-06-24 at 15.47.17.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/17e21345-2955-404f-a4c3-029cf1372e95)

I don't believe we have any usability testing data to suggest this is any better or worst than showing a placeholder with an example address (e.g. "jwgno32gh90arwagw08heg"). I suspect though that our developers are generally cognizant of what addresses look like, so perhaps placeholders like this one used in the wallet would be sufficient.


![Screen Shot 2019-06-24 at 15.53.37.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/59af517d-be45-4bc9-b3dc-f0228db6dc90)

**Comment by markmhx** [comment]
Looks good

<img width="448" alt="Screen Shot 2019-07-02 at 13 57 39" src="https://user-images.githubusercontent.com/28991/60511060-5e8e6900-9cd1-11e9-8e13-0563c6beb845.png">
