### ISSUE TITLE
Maker portal: Feedback on save

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#545]
I think there is a saved state text change on that button, but currently it is so fast I can't read/looks like a glitch. Suggest adding timeout on that, or just placing that text to the side of the button and have it persist. 

Kind of like this but swap positions: 

![Screen Shot 2019-06-21 at 2.20.59 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/7a2c7c00-d3b8-42f5-972a-b8a04ae5d93d)

**Comment by markmhx** [comment]
Closing this issue out since it appears to be redundant with https://github.com/blockstack/app.co/issues/533
