### ISSUE TITLE
Add missing links to Terms of Service to participation agreement on Maker Portal

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#547]
Noticed a few links missing at the end of the doc. 

> All of these Terms of service < link >

**Comment by hstove** [comment]
@GinaAbrams this has to be updated in Eversign. I should probably link to:

https://app.co/mining/terms
https://app.co/terms

**Comment by markmhx** [comment]
I'm adding this to the Maker Portal release with the assumption that it's a required change.

Can someone provide a link to the document in question?

**Comment by markmhx** [comment]
@GinaAbrams I'm not sure I'm clear on the required change here. Is this something you can change with Eversign?

**Comment by GinaAbrams** [comment]
@hstove Freddie just emailed us this copy. They will need to be updated on https://app.co/mining/terms
https://app.co/terms

Please let me know if you need anything updated in eversign.

**Comment by GinaAbrams** [comment]
@hstove Freddie just emailed us this copy. They will need to be updated on https://app.co/mining/terms
https://app.co/terms

Please let me know if you need anything updated in eversign.

**Comment by markmhx** [comment]
@GinaAbrams If we need to update copy on those two pages, we should create another issue (or two).

I believe this particular issues concerns the addition of links to the two terms pages from inside the Eversign document. Have these been added?

**Comment by GinaAbrams** [comment]
We should receive an updated version of participant terms today and then can update. Will create new issues for the other points.

**Comment by markmhx** [comment]
I'm not seeing any reference to our terms of service in the latest participation agreement in production. @GinaAbrams were these references removed or I'm just overlooking them?

**Comment by GinaAbrams** [comment]
Old issue.
