### ISSUE TITLE
Add more robust caching

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#549]
App.co currently has a CPU cache for storing API responses from the API server, as well as HTML renders for server-side rendering.

Two things would make this much better:

- Redis as a cache persistence layer. Because we use a CPU cache, we can only use one instance for the front-end server (due to cache clearing logic). This would allow us to scale horizontally, and persist the cache between refreshes.
- Some logic to warm up the cache. When an app is updated, the API server clears the CPU cache. It would be much better to let the cache warm up before making the entire cache cold.

**Comment by markmhx** [comment]
Is this an improvement you view as urgent for us to make soon? Or can it wait for a while?

**Comment by hstove** [comment]
I'm assigning @timstackblock and @markmhx to this for testing.

https://staging.app.co

There are no functionality changes. Testing this just means poking around the site, and making sure every page loads OK. You should also see some performance boosts, compared to what is on production right now. One big boost is when you go to the home page and then click on "App Mining" at the top. Still not instant, but it was taking >10s before.

**Comment by markmhx** [comment]
I'm a bit late to the party, but seems snappy 💥

**Comment by timstackblock** [comment]
This looks very good, fast loadtimes
