### ISSUE TITLE
Format Maker Portal pages for mobile

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#550]
Currently all the pages are quite squished within narrow viewports.

<img width="412" alt="Screen Shot 2019-06-24 at 15 07 48" src="https://user-images.githubusercontent.com/28991/60021233-eb15a780-9691-11e9-90a2-3906300733ed.png">

**Comment by markmhx** [comment]
@hstove Is this possible for launch?

**Comment by timstackblock** [comment]
Menu seems out fo place on mobile please see the image below

![Screenshot_20191209-102644_Chrome.jpg](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/a12de895-3a58-45e3-a905-545f350c1f28)
