### ISSUE TITLE
Several apps have broken images for avatars

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#552]
Several apps have broken images for avatars once you click the link the images at the top does not display

![Screen Shot 2019-06-25 at 10.26.06 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/a42d6608-e7d4-4c1b-a5c6-415cb19fb42b)![Screen Shot 2019-06-25 at 10.25.11 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/871ada4d-cca1-4773-9ae3-d2ad2567fcc5)![Screen Shot 2019-06-25 at 10.24.11 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/cbd9352c-9904-4b9f-bea1-3018695e408e)

**Comment by markmhx** [comment]
@hstove Is this just a data problem in that we have broken assets for some apps or is this an app problem?

**Comment by hstove** [comment]
This is just a staging data problem. No issues with our underlying production data. Closing it out.
