### ISSUE TITLE
Include private link in email given to new App Miners

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#554]
Currently setup through Zapier, might need to migrate off @cuevasm

**Comment by markmhx** [comment]
@jeffdomke @cuevasm could one of you provide more information on what this issue entails? I'm not sure if we're adding a new link, just swapping Zapier out somewhere, or what.

**Comment by markmhx** [comment]
Closing this out in favor of https://github.com/blockstack/app.co/issues/599
