### ISSUE TITLE
Collect audiences for TryMyUI from Maker Portal

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#559]
1. Tab needed
2. UI needed for explaining and capturing
3. Need some kind of process for sharing this information with TryMyUI – perhaps an email fires every times someone changes this. 

Assume we also need a new DB entry for this as well.

**Comment by markmhx** [comment]
I'm moving this to the icebox assuming it's a nice-to-have for now.

**Comment by markmhx** [comment]
I'm closing this out in favor of https://github.com/blockstack/app.co/issues/666
