### ISSUE TITLE
Add clear button to search bar

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#56]
- There should be a close icon in the search bar

**Comment by markmhx** [comment]
Let's place the same close icon that we're using in the "Get updates" modal with the following positions and sizes roughly for the search box:

## Desktop

<img width="976" alt="screen shot 2018-08-01 at 12 36 30" src="https://user-images.githubusercontent.com/28991/43517098-d89a1ba6-9587-11e8-901c-5f5cd3160e40.png">

## Mobile

<img width="488" alt="screen shot 2018-08-01 at 12 36 39" src="https://user-images.githubusercontent.com/28991/43517109-dcdf0992-9587-11e8-9e6f-8221e9db7423.png">

**Comment by markmhx** [comment]
Let's vertically align this within the search bar
