### ISSUE TITLE
Add Hello Bar script tag

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#57]
Will use to support app launches

<script src="https://my.hellobar.com/cefe56c097b8691a6036dcfe8feea1fd6c5c736b.js" type="text/javascript" charset="utf-8" async="async"></script>

Original issue: https://github.com/blockstackpbc/app.co/issues/62

**Comment by markmhx** [comment]
@hstove Can you release this today as a quick addition to the existing site and upcoming redesigned site so the marketing team can start using it on Monday?

**Comment by hstove** [comment]
Forgot to post my update, but this is live on production right now, and will also be in the redesign. So we should be good to use for an announcement.
