### ISSUE TITLE
Update terms on app.co 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#572]
@fjl4 sent us an email with the app mining terms: `Attached is a redline of the updated terms we'll need to post at https://app.co/mining/terms. The changes are all in Paragraph 7.`

**Comment by markmhx** [comment]
This is presumably urgent. @GinaAbrams @hstove was this email's changes incorporated and if so, can you forward me the email so I can QA?

If not, @hstove please assign yourself.

**Comment by hstove** [comment]
Just double checked - this is done 👍
