### ISSUE TITLE
Update guidance on "Payment Details" screen of Maker Portal

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#573]
Presently the payments are made in Bitcoin BTC. We anticipate paying in Stacks in the future. In order for your Stacks payment to start accruing for future delivery, please provide both BTC and STX address. cc @fjl4

**Comment by markmhx** [comment]
I'm moving this to the backlog since it doesn't appear completed. I assume @fjl4 has already approved this copy and it can be assigned to @hstove for completion.

**Comment by hstove** [comment]
Just checked - this is the same language that is in production :+1:
