### ISSUE TITLE
Update guidance for "Tax Documents" page of Maker Portal

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#574]
For US Person, please submit...

**Comment by GinaAbrams** [comment]
Upload documents as a US Person. 

For Non-US persons, use the applicable IRS Form: W-8 For natural persons or form W-8-E for entities.

**Comment by markmhx** [comment]
@GinaAbrams It's not clear to me just what changes are requested, but it seems as though what's currently live in production maps to your notes here. Can you verify that's the case?

![Screen Shot 2019-08-05 at 13.34.58.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/202a03fe-a611-4938-918b-9dc153f8845f)
![Screen Shot 2019-08-05 at 13.35.00.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/8bf4e548-d9fb-452e-b7d6-c0636a53dc6d)
![Screen Shot 2019-08-05 at 13.35.03.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/c7b6d60e-b1dd-437b-90b7-01f5e3e2c122)
