### ISSUE TITLE
Add important documents section below app mining status 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#575]
with link to offering circular and both participation agreements.

**Comment by markmhx** [comment]
This appears resolved by the "Important Links" section now available in the left-hand column:

![Screen Shot 2019-08-05 at 13.36.23.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/9e024e14-5a2a-4807-8993-cd7314e2ec76)
