### ISSUE TITLE
Add guidance for entities looking to register for App Mining

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#577]
something along the lines of "If you are looking to register for App Mining as an Entity, please email mining@app.co to be on-boarded." 

This should appear as both the start of the flow and the at the identity verification stage.

**Comment by markmhx** [comment]
@GinaAbrams I see the following copy on the "Identity Verification" page of the Maker Portal, but I don't see any such guidance earlier in the "Add your app" flow. Is this placement sufficient?

![Screen Shot 2019-08-05 at 13.38.14.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/05138642-cfad-43b2-9491-6607c7726dba)
