### ISSUE TITLE
Fix typo on "Identity Verification" page of Maker Portal

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#579]
Currently copy reads as: you are not eligible for app mining until you&ve completed identity verification.

**Comment by markmhx** [comment]
@GinaAbrams I'm not seeing a typo around this part of the "Identity Verification" page – is it still there or has been resolved?

![Screen Shot 2019-08-05 at 13.45.45.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/fdaaddec-9bae-4f69-a155-586df2bcad6f)
