### ISSUE TITLE
Confirmation email the same for app mining flow and general app.co flow

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#588]
**Describe the bug**
I just tested the app.co submission flow twice, once with Blockstack auth and once without. I successfully got a magic link. But I received two identical emails that look like the submission confirmation email for non-app mining apps.

**Comment by cuevasm** [comment]
Can you please forward, I just checked settings and they seem right assuming the column TRUE is still in place. That's what differentiates the two emails. You can either forward me or send along the test you were trying and what you wanted it to do. 

@hstove is there any reason not to move the emails over to you vs. having them come from Zapier at this point? That was just a quick solution, if you've got a SendGrid type thing going, might better to just put the emails and rules there.

**Comment by markmhx** [comment]
I'm getting the right App Mining email when submitting a Blockstack app so I presumed this has been fixed:

![Screen Shot 2019-08-07 at 15.04.14.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/355ea4ee-802c-4338-b01c-e72fff7c6a7c)
