### ISSUE TITLE
Send app miners an email with their magic link 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#589]
**Is your feature request related to a problem? Please describe.**
Right now, we only give app miners one opportunity to access their magic link. Would like to provide a back up. 

**Describe the solution you'd like**
Email the link? 

**Additional context**
Not sure about the security implications.

**Comment by moxiegirl** [comment]
@GinaAbrams this will require a documentation change on the work I am doing today.

**Comment by markmhx** [comment]
Closing this issue out in favor of https://github.com/blockstack/app.co/issues/599
