### ISSUE TITLE
Manually update e-sign status for apps

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#592]
Some apps may not have a properly synced e-sign status, if they signed right after we deployed. We can manually go through and make sure those are marked correctly in the app.co database.

**Comment by markmhx** [comment]
Is this a one-time adjustment or will we need to update manually upon future deployments? Are we aware of any specific apps that are currently reflecting incorrect statuses?

**Comment by GinaAbrams** [comment]
Voicestory is one app that needs to be updated please.

**Comment by hstove** [comment]
Updated 👍

**Comment by markmhx** [comment]
If this is an ongoing administrative concern (and not one of bulk updating apps historically but rather one-by-one going forward), it seems we should close this out in favor of an operational process.

**Comment by GinaAbrams** [comment]
It is not ongoing. @hstove do you know if there are other apps impacted? I would imagine there are.

**Comment by hstove** [comment]
I do not know of any, and all the reports I've seen have been fixed.
