### ISSUE TITLE
App.co/mining DevOps issues

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#595]
**Describe the bug**
Multiple times over the past few months app.co has not loaded on the first try. 

**Expected behavior**
It should load on the first try. 

Past issues listed here: 
July 16th: 
<img width="565" alt="Screen Shot 2019-07-31 at 11 10 44 AM" src="https://user-images.githubusercontent.com/30627583/62223979-deb4f680-b383-11e9-945a-e5cd4709f0d5.png">

July 29th: 
<img width="696" alt="Screen Shot 2019-07-31 at 11 13 59 AM" src="https://user-images.githubusercontent.com/30627583/62224261-5b47d500-b384-11e9-80f6-39ab9a4ad0aa.png">

July 31st 
<img width="1374" alt="Screen Shot 2019-07-31 at 10 44 21 AM" src="https://user-images.githubusercontent.com/30627583/62223954-d2309e00-b383-11e9-9a60-65e45c09b181.png">

**Comment by markmhx** [comment]
I'm closing this out since it's captured more recently with https://github.com/blockstack/app.co/issues/785
