### ISSUE TITLE
Some apps not registered in admin panel despite going through the app.co submission flow. 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#597]
**Describe the bug**
There are some apps that appear in the app mining submission sheet but don't successfully get added to the admin panel. It has happened approximately 5 times over the past few months. 

**To Reproduce**
It seems to be based on certain types of emails. 

**Expected behavior**
We shouldnt have to submit apps for or request app owners to re-submit. 

Example: Blockstack Authenticator app.

**Comment by markmhx** [comment]
@GinaAbrams Have you continued to encounter this bug? And if so, any idea which types of emails lead to this problem? @kyranjamie and I are unclear just how to recreate this problem and fix at the moment.

**Comment by hstove** [comment]
Apologies for not updating this issue. We did narrow it down to an issue where our mailing list provider would reject the call to 'subscribe' the user if the provider thought the email was a fake address. I added logic so that, if that happened, the app submission would still go through.
