### ISSUE TITLE
Include link to Maker Portal in app submission confirmation email

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#599]
Currently, if developers don't record the link to the Maker Portal upon app submission, they have to contact us to retrieve it.

Including it in the following confirmation email could make it easier for developers to retrieve and use:

![Screen Shot 2019-08-05 at 14.54.46.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/e2818a48-30af-480f-a0ba-d07cda4b33cf)

**Comment by markmhx** [comment]
Ok yea, agreed. And if we replace this with Blockstack auth (https://github.com/blockstack/app.co/issues/598), then the URL will become standard anyway.

**Comment by markmhx** [comment]
I've updated this issue to reflect how we're removing the magic link and planning to release a Portal redesign in which the portal's URL is standardized.

I'm assigning to @kyranjamie who will assign this issue to @cuevasm with guidance once we go live with the new Portal design and have that URL's value confirmed, so that @cuevasm can subsequently update this mailer with a link to it.

**Comment by markmhx** [comment]
@kyranjamie has integrated this change on staging and will post a screenshot of the expected result here.

**Comment by timstackblock** [comment]
There is no link to the Maker Portal in the current email


![Screen Shot 2019-12-09 at 10.42.42 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/d50c39e3-7123-4bd0-b646-cb522f1bf10b)

**Comment by kyranjamie** [comment]
Hey @moxiegirl, here is the proposed changes to the email. Can you please check the wording and let me know if there is anything else you'd like added.

![image.png](https://images.zenhubusercontent.com/5d765e279cf7af0001b78a5e/36abb0f9-728d-47d6-ac10-fef526f8defa)

**Comment by markmhx** [comment]
@timstackblock Apparently with Zapier we can't integrate any kind of staging-only email here so will have to save the changes with Zapier that update this email once we're live in production.

**Comment by moxiegirl** [comment]
@kyranjamie From the earlier comment, I think you have to work with @cuevasm first on the content here. Or did you already do that?



> I've updated this issue to reflect how we're removing the magic link and planning to release a Portal redesign in which the portal's URL is standardized.
> 
> I'm assigning to @kyranjamie who will assign this issue to @cuevasm with guidance once we go live with the new Portal design and have that URL's value confirmed, so that @cuevasm can subsequently update this mailer with a link to it.

**Comment by moxiegirl** [comment]
@kyranjamie Proposed text, I did not check the HTML syntax.

```


Your Blockstack app was submitted successfully, great work, and thank you. If you wish to enter your app in the App Mining program, you must take <strong>further action</strong> to ensure you're fully registered before the next deadline. Just choose <a href="https://app.co/maker/apps" target="_blank"><strong>Manage your apps</strong></a> from the App.co menu to navigate to your app and complete your registration. 
<br><br>

You must provide payment details, identity verification information, and legal documents to complete your registration. Our team reviews all submissions promptly!  <strong>After completing your registration materials </strong> and waiting 1 -2 business days, you can begin <a
href="https://app.co/mining/apps" target="_blank">checking to see if your app is eligible</a>. You'll also receive an email from
our team confirming receipt of registration materials, and at the start of the next ranking.

<br><br>

In the meantime, if you have any questions, please don't hesitate to reply to this email (or use mining@app.co)
or check out the <a href="https://github.com/blockstack/app-mining">App Mining Github repo</a>.
<br><br>

<strong>Other Resources:</strong>

<ul>

<li>Learn more about how <a href="https://blog.blockstack.org/app-mining-game-theory-algorithm-
design/">App Mining ranking works</a></li>

<li><a href="https://app.co/mining/latest">Meet the top earners from last month</a></li>

<li>Check out the <a href="https://forum.blockstack.org/">Blockstack Forum</a> for any support needs</li>
<li><a

href="https://join.slack.com/t/blockstack/shared_invite/enQtMzYyMDAxODg3MTg1LWJhODk4YzYwNjAOY2JiNTU
yNDhmZTViZTYONmlOOWYOMWVhZjMOODY1YjhiMzEwMDk4ZGE2NWI4ZmEOMjcxYWI">Join us on Slack</a>to
connect with the community</li>

</ul>

<br>
```

**Comment by kyranjamie** [comment]
Thanks @moxiegirl, looks good. Will update this on launch.
