### ISSUE TITLE
Add toggle to manually indicate that Identity Verification has gone through 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#602]
**Is your feature request related to a problem? Please describe.**
Some people are having difficult going through identity verification even after 3x. After talking to legal, we can do this manually in some instances. 

**Describe the solution you'd like**
A checkbox that can indicate whether or not the ID verification has gone through a manual process.

**Comment by hstove** [comment]
How does this 'manual' process actually work? And what is the issue in the first place?

If there is a bug on the app.co side that prevents them from even going through the flow, we should fix that. If they are unable to complete the KYC flow after getting started (perhaps due to fuzzy images), then how would we do this manually and make sure that the ID is valid?

**Comment by GinaAbrams** [comment]
It is not due to app.co, it's a Netverify thing. One person went through the flow 3x. The picture was not fuzzy on Netverify. There is a manual process we can do in the event of issues like these, confirmed by Freddie. I think it would be for a very small population of folks, but the ability to indicate this on the admin panel would be very helpful in those unique cases.

**Comment by hstove** [comment]
Hey @GinaAbrams , assigning to you for testing on https://staging.app.co . I just used checkboxes like our other things, such as tax info. You can manually turn this on/off as needed.

**Comment by timstackblock** [comment]
@hstove Is this ready for QA

**Comment by GinaAbrams** [comment]
@hstove I think there's something I'm missing, can you break down if there are any special circumstances with this or what I should be testing? 

I just checked three apps and they all seem to not have gone through the process or provide access to jumio or  even when i am 100% sure one has (ezresize, which is currently listed as ready). The STX address didn't seem to translate through either. 

The buttons to access in Jumio and Eversign are no longer showing, or the reset function.
