### ISSUE TITLE
Remove "Claim This App" Text 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#605]
**Is your feature request related to a problem? Please describe.**
*All* the apps on app.co have a "claim this app" line on them, which is misleading in the following ways: 1) doesn't reflect the that apps have been submitted by founders and 2) there's no action an admin can take that removes the copy when people want to claim the app.  

**Describe the solution you'd like**
Only list "Claim This App" for apps that are submitted by someone that marks "someone else made this app" in the registration flow.

**Comment by markmhx** [comment]
This appears to be getting tackled with https://github.com/blockstack/app.co/pull/648
