### ISSUE TITLE
Update logic around what "Mining Ready" means

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#609]
Currently, we have `/mining/apps`, where you can see whether an app is fully registered for app mining. However, we have some new information that is required for the next phase with Stacks payments. We need to reflect this page, as well as relevant admin pages, to use the new required information.

**Comment by markmhx** [comment]
@hstove By `relevant admin pages`, do you mean specifically the pre-populated sheet available to admins for download? Are there other admin touch points affected here?

**Comment by hstove** [comment]
@GinaAbrams I'm assigning this to you. I've done testing on staging, but it's hard to test without real data. The logic for determining 'mining ready' is currently on the production server (https://app.co/mining/apps). I could use your help with making sure it's all set.

2 things to test:

- https://app.co/mining/apps . The ready / not ready should be accurate, based on the new logic
- On https://app.co/admin/mining, which you download all apps, it should only include apps that are "ready" on the /mining/apps page.

**Comment by GinaAbrams** [comment]
@hstove this looks set on app.co/mining/apps, but getting an internal server error on app.co/admin/mining

**Comment by hstove** [comment]
Oh whoops, that's the wrong link. It's https://app.co/admin/mining/months

**Comment by hstove** [comment]
Ping @GinaAbrams for following up and potentially closing this out.
