### ISSUE TITLE
Update copy on homepage of mining

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#611]
Change text under the shuffling cards to 'Learn how to earn' or something similar. The main issue is with the 'win' language, want to always reinforce that this is an earned payout, and game language makes it feel like less of a serious program or funding/feedback mechanism. There are game mechanics at play but winning is exclusive language, everyone earns in this program.

![image (4)](https://user-images.githubusercontent.com/6131188/63058648-1a7eae80-bea2-11e9-8323-c573872e53d6.png)

**Comment by hstove** [comment]
@kyranjamie I'm assigning this to you. It's just a minor change, we want to update "Learn how to win" to "Learn how to earn"
