### ISSUE TITLE
Admin Panel Copy Change 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#613]
Can we change copy "Please upload your tax documents via Dropbox." to "Please upload your tax documents via Dropbox. **_Documents will only be marked accepted if they are uploaded as the name of your app_**."

cc @markmhx -- can we please make this super high priority. Since people have less contact  with me in our new registration flow, I don't know what name to look under to connect the forms I am receiving with the app. It is making the process a lot more time consuming from an admin perspective, and a small change can help a lot. 🙏

**Comment by hstove** [comment]
@GinaAbrams it's live, please verify on your end. Thanks!

**Comment by GinaAbrams** [comment]
You da 💣 thank you @hstove !
