### ISSUE TITLE
Add Blockstack auth to app submission page

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#621]

**Comment by timstackblock** [comment]
I am prompted to auth with block stack when I submit an app but after I auth and come back into app.co I still see the Auth With Blockstack Button.

https://screencast-o-matic.com/watch/cqXqF9UOHm

**Comment by timstackblock** [comment]
Moving this back to in progress @kyranjamie

**Comment by timstackblock** [comment]
This is still broken for me moving back to in progress

**Comment by markmhx** [comment]
@timstackblock Can you check this one again?
