### ISSUE TITLE
Claim your app link is blocked by Cloudflare

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#638]
Clicking 'Claim it now' on any app triggers Cloudflare protection. We should find a more user-friendly way of doing this or perhaps just linking this to a form where they can request changes more simply (happy to setup)

![image](https://user-images.githubusercontent.com/6131188/66358562-3cd3fc00-e928-11e9-8aed-932f588932c0.png)

![image](https://user-images.githubusercontent.com/6131188/66358573-4e1d0880-e928-11e9-825e-ca87fb5b928e.png)

**Comment by kyranjamie** [comment]
The Claim it now is a `mailto:` link, so this shouldn't trigger anything server side. Could this be related to the default mail client you have set up on your device @cuevasm ?

**Comment by GinaAbrams** [comment]
I just was in admin panel and noticed this message about cloud flare pop up. Not sure if related but in case its helpful: 
<img width="1386" alt="Screen Shot 2019-10-15 at 9 33 19 AM" src="https://user-images.githubusercontent.com/30627583/66836186-e7eb4380-ef2e-11e9-9348-e2991e225b5e.png">

**Comment by hstove** [comment]
@GinaAbrams , I'm not seeing anything about Cloudflare in there? That error message probably comes from one of the third party tracking scripts on app.co.

**Comment by hstove** [comment]
I think we should just remove this link. New apps will already have 'claimed' their app, and existing App Mining apps will get comms about how to claim their app.

**Comment by GinaAbrams** [comment]
> I think we should just remove this link

+1 !
