### ISSUE TITLE
Redesign app navigation

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#640]
Currently, the only way to sign in with Blockstack is on the _submit your app_ and _claim an app_ pages. We need to also allow people to login if they visit `/maker` directly. We also likely want people to be able to logout.

[See Paper doc for more info](https://paper.dropbox.com/doc/App.co-Maker-Portal-redesign-specification--Ant_yZ7lr8zt0ETFwDJCAA4NAg-qpHNG3Y1Q0GILenxlxcuR#:uid=450694253716659063394923&h2=App)

**Comment by jasperjansz** [comment]
@hstove I've added a design of what I think the app.co menu should include:
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=2949%3A3658

This includes sign in/out links, and a link to the developer portal once signed in. 

In the case people navigate to the developer portal URL directly without being signed in we can prompt them to sign in: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=2949%3A4699

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/3f23bfcc-1d44-4fa1-ab7f-ec69b2a998a4)

**Comment by hstove** [comment]
Thanks, @jasperjansz . I've added Kyran as the assignee and moved it back to the Backlog.

**Comment by timstackblock** [comment]
This is broken signing in from the staging.app.co/maker page throws a 500 error

![Screen Shot 2019-12-04 at 9.57.37 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/8134a4e4-1696-457b-92ca-1da5ab9d8212)

Video of bug
http://somup.com/cqlf2PfUq4

**Comment by kyranjamie** [comment]
Really confused here. I'm unable to replicate any of these issues. Is this an intermittent issue, @timstackblock ?

**Comment by markmhx** [comment]
@timstackblock I just failed to recreate this. Mind trying?

**Comment by timstackblock** [comment]
This is resolved
