### ISSUE TITLE
Add "Gaia testing instructions" section to edit app page

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#646]
**Is your feature request related to a problem? Please describe.**
As initially requested in https://github.com/blockstack/app-mining/issues/149, App Mining reviewers need instructions provided by developers via the edit app page that they can use to test an app's usage of Gaia.

**Describe the solution you'd like**
Upon visiting the edit page on App.co, an app owner can submit these instructions. And these instructions will subsequently appear on the app's page in the admin panel.

These instructions should be provided in a single text area input with instructions along the lines of "Please describe below how your app uses Gaia to store user data. Specify what features of your app do or do not store data in Gaia and where those features can be found in the user interface."

The design for this feature should be reviewed by @larrysalibra before integrated and released.

[See design](https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=3360%3A714)

**Additional context**
This issue is intended for execution after we have redesigned the Maker Portal even though the change is included generally in that redesign's design materials in Figma.

**Comment by markmhx** [comment]
@larrysalibra How does the below prompt look to you for satisfying this issue's request?

<img width="429" alt="gaia-testing-instructions" src="https://user-images.githubusercontent.com/28991/68085123-90f5d180-fe3d-11e9-9333-8ab829e57e56.png">

**Comment by larrysalibra** [comment]
This looks great to me! Thanks.

**Comment by moxiegirl** [comment]
Which may translate better than what in the above.

"What and which are often used interchangeably, but there is a subtle difference. Which refers to specific items and what to general things."
