### ISSUE TITLE
Invalid link to full report on /mining

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#649]
Reported from email (not able to test right now):

1. Go to /mining
2. Click "view full report"
3. URL is invalid, date param is `Invalid%20Date`

**Comment by markmhx** [comment]
I'm not seeing a "View full report" option, though with "See full report", the format appears to be fine regardless of the month I've selected:

![Screen Shot 2019-10-28 at 14.13.45.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/1ac82232-0ce8-45ca-b7d2-4c1e57f992a6)

Could this possibly be browser-specific?

**Comment by hstove** [comment]
Yep, couldn't repro on Safari, Firefox, or Chrome. Closing.
