### ISSUE TITLE
Improve loading screens for Maker Portal

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/app.co#651]
The current loading screens are a bit bare.

![image.png](https://images.zenhubusercontent.com/5d765e279cf7af0001b78a5e/df7ffd41-a472-470e-80aa-286f7ea03f27)

A reusable loading place card/screen pattern is needed.

@jasperjansz @markmhx Input welcome. Maybe this could be a section of the design system?

**Comment by markmhx** [comment]
Might it work to use the transition indicator on this screen, leaving the rest of the page below the app navigation simply blank until content loads?
