### ISSUE TITLE
Sub-navigation for app management pages

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/app.co#659]
Implement new [sub nav designed here](https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=3419%3A1985)

[See Paper doc for feature specs](https://paper.dropbox.com/doc/App.co-Maker-Portal-redesign-specification--Ant_yZ7lr8zt0ETFwDJCAA4NAg-qpHNG3Y1Q0GILenxlxcuR#:uid=144434338256101593797870&h2=Manage-apps)

**Comment by markmhx** [comment]
@kyranjamie Is this complete?

**Comment by kyranjamie** [comment]
Yes, it's on staging.
