### ISSUE TITLE
Add Product Hunt URL to app submission and edit pages

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#663]
Empower app owners to provide a Product Hunt URL while submitting their app and later editing it.

**Comment by moxiegirl** [comment]
@markmhx I thought app mining no longer supported Product Hunt? Gina asked me to remove them several days ago: https://github.com/blockstack/docs.blockstack/issues/422

**Comment by GinaAbrams** [comment]
This is a different use of Product Hunt and not yet a required change. Let's please icebox or close for now. Thanks!
