### ISSUE TITLE
Replace Dropbox with Eversign for "Legal documents" section of edit app page

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#665]
**Is your feature request related to a problem? Please describe.**
Currently, we use Dropbox for uploading tax forms within the context of the "Legal documents" section of the edit app page for App Mining. 

Eversign is a cleaner method for signing and submitting documents than Dropbox so she be used instead.

**Describe the solution you'd like**
Change the button from "Upload via Dropbox" to "Open Tax Form" and have it trigger the standard Eversign modal used elsewhere on this page, displaying the relevant tax form for completion and submission.

[See the design here](https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=3360%3A1396)

**Additional context**
This issue is intended for execution after we have redesigned the Maker Portal even though the change is included generally in that redesign's design materials in Figma.

**Comment by diwakergupta** [comment]
FWIW Dropbox does have a good HelloSign integration (Dropbox acquired HelloSign last year), in case that influences the thinking / pricing here.
