### ISSUE TITLE
App Mining latest payout schedule

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/app.co#675]
Is the app mining payout schedule listed at https://app.co/mining the latest updated version?

> the total monthly payout in STX will begin in November at $500,000; and will increase to $700,000 in February 2020

**Comment by markmhx** [comment]
What's the correct / latest payout schedule? It's unclear how this copy should be changed without knowing.

I'm assigning this to @GinaAbrams since I presume she knows best.
