### ISSUE TITLE
Maker Portal Redesign: Issues found During Doc scoping

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#681]
## 11/13/2019

 - [x] Pushing submit when not signed in with a Blockstack ID should return an error: it doesn't _I may have killed the deployed server doing this_  

## 11/14/2019

- [ ] After choosing *Sign In with Blockstack* I am returned to the application page and the button still reads *Sign In with Blockstack* ; maybe the button should go away and just show *Signed in with meepers.id.blockstack* --- then after a moment; the page read *Sorry, we couldn't find this page*  -- I was in incognito mode

## 11/15/2019

- [x] After *Sign in with Blockstack* I press the **Submit your app** button and get an error saying I wasn't signed in. 

- [ ] After choosing Blockstack Auth and **Submit your app** I am told that I did not choose Blockstack auth

![image](https://user-images.githubusercontent.com/1347209/68969050-ea90c100-0798-11ea-964b-f76692273d2f.png)

**Comment by kyranjamie** [comment]
Thanks for this @moxiegirl, fixed in above commit.

**Comment by moxiegirl** [comment]
@kyranjamie I've checked the one that is fixed -- the rest are outstanding.

**Comment by moxiegirl** [comment]
I'm going to file individual issues from here on out.

**Comment by moxiegirl** [comment]
@timstackblock I am seeing this Blockstack Authentication issue, are you?

**Comment by markmhx** [comment]
The 11/15 issue is being tracked separately here: https://github.com/blockstack/app.co/issues/713

@timstackblock can you confirm whether the 11/14 issue is still outstanding? If not, I believe we can close this issue.
