### ISSUE TITLE
Add updates to Note: section in Awario App Mining docs

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#684]
![image](https://user-images.githubusercontent.com/6131188/69167650-9a499400-0af5-11ea-8d9e-9665eee72d26.png)
https://docs.blockstack.org/develop/app-reviewers.html#awario

update to --> 

Important Notes: 
- To make sure Mentions on Instagram are picked up, set your account to a ‘Business’ account. This is very easy → [Change to Business](https://help.instagram.com/502981923235522)
- Medium links will not count in your Reach score for the time-being. The way Reach is calculated currently on Medium.com is too clumsy. Awario is shipping updates to this soon, so we can revisit then. Medium Reach will be zeroed out for everyone [as per this ticket](https://github.com/blockstack/app-mining/issues/171). 
- If you change your app name, you need to let us know. Email mining@app.co to start the process. Note that it will mean a month not getting an Awario score as we setup a new query and train it. 
- Please wait until the audit period to contact us about Mentions you feel are missing. In all the cases where someone has reached out, the Mentions show in the dashboard later as there is a delay as data is processed- your Awario dashboard is not meant to be real-time.

**Comment by moxiegirl** [comment]
This is done. See https://github.com/blockstack/docs.blockstack/pull/456
