### ISSUE TITLE
message switches back & forth thru "Sign-in" with "you do not have any apps" 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#685]
**Describe the bug**
Users who sign-in with the Blockstack app, and attempt to manage an app but do not have any apps to manage will see a screen that switches back and forth from "Sign-in with Blockstack" to a message that says " you do not have any apps to manage" 

Video of issue
https://screencast-o-matic.com/watch/cqXqFQUOCA

**To Reproduce**
1. Go to 'app.co' staging
2. Click on 'manage your app' you will be prompted to login with Blockstack
3. Scroll down to 'Auth bith blockstack and follow the flow into the blockstack browser
4. When the error is take back into app.co You will see the error and the screen toggle back and forth.

**Expected behavior**
The message should not toggle back and forth and the user should be told they do not have apps to manage

**Screenshots**
<img width="1012" alt="Screen Shot 2019-11-19 at 1 22 11 PM" src="https://user-images.githubusercontent.com/49165468/69174377-ac184080-0acf-11ea-8cbe-3a3f03c3cfbe.png">

<img width="1289" alt="Screen Shot 2019-11-19 at 1 21 28 PM" src="https://user-images.githubusercontent.com/49165468/69174384-b20e2180-0acf-11ea-8478-b8eadadfd7d8.png">

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [ 78]

**Comment by kyranjamie** [comment]
@timstackblock this should be fixed following auth refactoring
