### ISSUE TITLE
If the user fails at uploading an image they cannot gracefully leave the page

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#699]
**Describe the bug**
If the user fails at uploading an image they cannot gracefully leave the page, and if they refresh the page or click the link to manage an app again and attempt to upload thier ID the page is stuck on this error message.

Video of the issue http://somup.com/cqX3bbfrdv

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1285" alt="Screen Shot 2019-11-22 at 11 24 21 AM" src="https://user-images.githubusercontent.com/49165468/69446436-6901db80-0d22-11ea-9a40-fa50b15c8051.png">

**Desktop (please complete the following information):**
 - OS: [ iOS 10.14.4]
 - Browser [chrome 78i]

**Smartphone (please complete the following information):**
 - Version https://app-co-staging-pr-633.herokuapp.com/

**Comment by markmhx** [comment]
Please test again now that we've changed this behavior to open the document in a new browser tab instead of a popup.
