### ISSUE TITLE
Add your Dapp modal - copy changes

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#7]
![Screen Shot 2018-05-16 at 5:21 PM](http://marker.screenshots.prod.s3.amazonaws.com/828df7d78e61408db3aa424c10caadfa-1526491298044.png)
---
### More Info

**Source URL**: [http://app-co.herokuapp.com/#](http://app-co.herokuapp.com/#)

**Comment by shea256** [comment]
Also:

Add the ability for people to add blockchains, storage systems, and auth protocols that aren't in the pre-defined list:

<img width="617" alt="screen shot 2018-05-16 at 1 26 10 pm" src="https://user-images.githubusercontent.com/994646/40133123-c8f84a40-590c-11e8-869e-d30b3a92c456.png">
