### ISSUE TITLE
Reviewer preference & Gaia testing instructions not present on app but in Figma

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#700]
**Describe the bug**
Reviewer preference & Gaia testing instructions not present on app but in Figma

**Expected behavior**
App has all functionality as Figma

**Screenshots**

FIGMA 

<img width="234" alt="Screen Shot 2019-11-22 at 12 38 03 PM" src="https://user-images.githubusercontent.com/49165468/69447791-40c7ac00-0d25-11ea-8f73-ac0cedeacab0.png">

CURRENT APP

<img width="1289" alt="Screen Shot 2019-11-22 at 11 27 19 AM" src="https://user-images.githubusercontent.com/49165468/69447826-4f15c800-0d25-11ea-81ad-c3d8c48ecda8.png">

**Comment by markmhx** [comment]
These instructions are intentionally omitted from this release despite being present in Figma.
