### ISSUE TITLE
Is this your app? Claim it now does not work as expected.

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#702]
**Describe the bug**
Is this your app? Claim it now does not work as expected.

**To Reproduce**

**Expected behavior**

**Screenshots**

Claim it now link
<img width="633" alt="Screen Shot 2019-11-22 at 12 57 36 PM" src="https://user-images.githubusercontent.com/49165468/69448983-c6e4f200-0d27-11ea-8e1a-42c7a320fbad.png">

 Link takes a user to an email pop up
<img width="1334" alt="Screen Shot 2019-11-22 at 12 50 46 PM" src="https://user-images.githubusercontent.com/49165468/69449056-f3007300-0d27-11ea-8735-56a2d6971336.png">

Figma Claim it now functionality not present
<img width="328" alt="Screen Shot 2019-11-22 at 12 54 03 PM" src="https://user-images.githubusercontent.com/49165468/69449083-04497f80-0d28-11ea-8d17-067120836a15.png">

**Desktop (please complete the following information):**
 - OS: [ iOS 10.14.4]
 - Browser [chrome, Ver78.0.3904.108 ]

**Comment by kyranjamie** [comment]
This isn't quite how the functionality should work. They previously got the maker link when they submitted the app. Now the app is tied to a Blockstack id, we only need it for legacy purposes.
You can test via the maker link in the admin page of an app.
Closing this for now, we've removed the _Claim it now_ link anyway
