### ISSUE TITLE
received email participation agreement was signed but box not checked as signed in admin panel

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#705]
**Describe the bug**
Received email participation agreement was signed but box not checked as signed in admin panel

**To Reproduce**
1. Create an app an sign the participation agreement
2. Login to the admin panel take a look at the app that was created
3. Scroll down to look at the section for KYC and signed documents
4. All boxes are unchecked

**Expected behavior**
The box should be checked if the agreement was signed is this a manual action or does this happen automatically

**Screenshots**

<img width="701" alt="Screen Shot 2019-11-24 at 7 46 06 PM" src="https://user-images.githubusercontent.com/49165468/69504724-512d8180-0ef3-11ea-9403-b47b58c40845.png">

<img width="1141" alt="Screen Shot 2019-11-24 at 7 45 52 PM" src="https://user-images.githubusercontent.com/49165468/69504808-ec265b80-0ef3-11ea-9f53-fbaeb7e243c0.png">

**Comment by markmhx** [comment]
@kyranjamie thinks this would be best to test this in production given the difficulties with doing so in development or staging, and given that it's a low-risk change (i.e. if it breaks in production, only @GinaAbrams will need to wait for a fix, not any developers or users). @timstackblock does that sound like a good plan to you?
