### ISSUE TITLE
App.co not picking up certain app registrations

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#707]
Certain apps that try to register only are registered to an email list as opposed to in the app mining admin panel. E.g. Cheery is in our database as an app that tried to register, but is not in the app.co admin panel anywhere. It appears this person tried to register twice already. I think this error had appeared in the past and been solved.

**Comment by hstove** [comment]
We will need more details from Cheery to determine exactly why this bug is happening for them. I'd assume it's something to do with some information they're entering, but right now I have no idea, since it is working for other people.
