### ISSUE TITLE
Submission Form uses both App or application 

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#710]
**Describe the bug**
**Screenshots**

Use App or Application consistently in this dialog

![image](https://user-images.githubusercontent.com/1347209/69995645-55662a00-1505-11ea-8aa0-d7eaaafe066e.png)

**Comment by markmhx** [comment]
@jasperjansz says we should use "App" consistently. We should change this specifically to "App's Twitter handle".
