### ISSUE TITLE
User receives app.co email even if submission is blocked by an error

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#712]
**Describe the bug**
User receives app.co email even if submission is blocked by an error and hits the submit button but does not successfully submit the app on the front end
**To Reproduce**
1. Go to submit an app
2. Enter all required fields
3. Scroll down to submit app and the app will not be submitted but the email will still send

**Expected behavior**
Either the app should not send the email if the submission is not valid
Or the form should not error if the submission is valid 
both should not happen 

**Screenshots**
<img width="544" alt="Screen Shot 2019-12-03 at 10 10 01 AM" src="https://user-images.githubusercontent.com/49165468/70079051-f0c4d100-15d1-11ea-861d-23afdd1196fd.png">

<img width="1124" alt="Screen Shot 2019-12-03 at 1 46 48 PM" src="https://user-images.githubusercontent.com/49165468/70079795-6da47a80-15d3-11ea-9d1a-f5a845bda96f.png">

**Desktop (please complete the following information):**
 - OS: [ iOS 10.14.4]
 - Browser [ chrome, 78.0.3904.108

**Comment by timstackblock** [comment]
@moxiegirl please add any details you would like about the email

**Comment by kyranjamie** [comment]
Hey @timstackblock @moxiegirl can you let me know which fields exactly were filled out to replicate this problem?

**Comment by markmhx** [comment]
Assigning back to @timstackblock for now until we can get more recreation details
