### ISSUE TITLE
Error message "Blockstack Authentication is required to participate in App Mining is set in by default" 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#713]
**Describe the bug**
Error message "Blockstack Authentication is required to participate in App Mining is set in by default" its present as soon as you come to the page and nothing you do will remove the error. Even setting the correct field to blockstack will not remove the error and this blocks app submission

**To Reproduce**
1. Go to app.co
2. Click on submit an app
3. Scroll down to the bottom of the page and you will see the error message as soon as you are put on the page
4. Attempt to fill in all field s and hit submit and you will see the error

**Expected behavior**
The error message should only appear if blockstack is NOT selected as the authentication

**Screenshots**
<img width="756" alt="Screen Shot 2019-12-03 at 10 17 59 AM" src="https://user-images.githubusercontent.com/49165468/70080570-ccb6bf00-15d4-11ea-86ee-07e01917ee10.png">

<img width="544" alt="Screen Shot 2019-12-03 at 10 10 01 AM" src="https://user-images.githubusercontent.com/49165468/70080538-c0cafd00-15d4-11ea-93dd-3e473f006716.png">

**Comment by timstackblock** [comment]
@moxiegirl  here is the bug from this morning screen share.

**Comment by jasperjansz** [comment]
@kyranjamie https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=3360%3A2050

Updated to use 'field with help text' pattern from the design system

**Comment by markmhx** [comment]
@timstackblock Can you check this one again? The design has been updated.
