### ISSUE TITLE
500 error that won’t allow be into staging.app.co when a user selects option to create a new blockstack ID

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#714]
**Describe the bug**
When a user selects the option to create a new Blockstack ID when authorizing authentication from the submit an app page  I get a 500 error that won’t allow be into staging.app.co or to complete the process of submitting to app.co after creating a new Blockstack id

Video of bug: http://somup.com/cqle2dfuT8

**To Reproduce**
1. Go to staging.app.co
2. Click on submit an app
3. When you get to the page select the blue button at the top of the page to auth with blockstack browser
4. When auth-ing with blockstack browser choose the option to create a new blockstack ID and the user will run into the 500 error as displayed in the video.

**Expected behavior**
This path should bring the user back to the page to submit their app without error.

**Screenshots**

<img width="1285" alt="Screen Shot 2019-12-03 at 2 32 17 PM" src="https://user-images.githubusercontent.com/49165468/70083082-c37c2100-15d9-11ea-84ec-df6e974ddfee.png">

<img width="1288" alt="Screen Shot 2019-12-03 at 9 43 24 AM" src="https://user-images.githubusercontent.com/49165468/70082708-fd98f300-15d8-11ea-9dee-ece46eccefe8.png">

<img width="1281" alt="Screen Shot 2019-12-03 at 9 42 29 AM" src="https://user-images.githubusercontent.com/49165468/70082727-0689c480-15d9-11ea-897d-d9c51c095337.png">

**Comment by markmhx** [comment]
@timstackblock Can you test this again and see if the behavior continues? @kyranjamie believes this may have been due to a one-off deployment issue.
