### ISSUE TITLE
Mystery reviewer test page

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#717]
[![Screenshot_2019-12-04_14-39-13.png](https://mrkr.io/s/5de7c51195f96249043d5dc4/2)](https://mrkr.io/s/5de7c51195f96249043d5dc4/0)

Need a page to test the mystery reviewer mechanic. This is for testing only and this change will likely never need to be deployed in production. Information these testers need is only app icon, name, description, and link to the app. 

We can remove everything else (see screenshot). 

Ideally, this page renders the apps in a random order every time it is loaded, this way we can assure each reviewer is unbiased by the order of the apps. 

---
### More Info

**Source URL**: [https://app.co/mining/october-2019](https://app.co/mining/october-2019)

<table><tr><td><strong>Browser</strong></td><td>Chrome 78.0.3904.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1680 x 1050</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1680 x 1027</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by kyranjamie** [comment]
Made a spreadsheet with requested data. Closing out.
