### ISSUE TITLE
Clicking on Submit your app never returns a success or completion

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#719]
**Describe the bug**
Clicking on Submit your app does not return a success or completion notice

**To Reproduce**
1. Go to https://staging.app.co/submit-your-app?
2. Fill out the submission
2. Click on **Submit your app**.

**Expected behavior**

**Screenshots**
http://somup.com/cqlfoKfU3V

**Desktop (please complete the following information):**
 - OS: Mac
- Browser Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

cc: confirmed by @timstackblock

**Comment by markmhx** [comment]
Mind confirming this bug is still occurring? @kyranjamie fixed some deployment issues that may have resolved it

**Comment by moxiegirl** [comment]
@markmhx I am not encountering this any more.
