### ISSUE TITLE
Fix links that aren't anchor tags for new tab click behavior

### ISSUE THREAD

**Issue by wbobeirne** [blockstack/app.co#72]
From @shea256 
> hey folks, app dot co hijacks my new tab clicks when I do "command-click" on a mac

Next only maintains this behavior if the item clicked is an anchor tag (see https://github.com/zeit/next.js/blob/canary/lib/link.js#L45.) Anything that uses <Link> should have an <a> tag under it to maintain this behavior.

**Comment by hstove** [comment]
👍I’ve tried to make most links anchor tags, I might have missed a place or two. We’re doing a whole redesign and this is something we’re focusing on. If there is a specific example I can fix it real quick.

**Comment by markmhx** [comment]
I'm closing this out since we're tackling the problem over here on another issue: https://github.com/blockstack/app.co/issues/46
