### ISSUE TITLE
App.co/mining copy changes 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#720]
@kyranjamie would it be possible to make the copy changes outlined here? https://paper.dropbox.com/doc/App.comining-page-updates--Ao8m2wO~MdBPYJW7Lvje~fx3Ag-aSnFBmqJfhtoRn4QIOPSk

**Comment by markmhx** [comment]
@GinaAbrams Any particular timing need for this? Urgent or just asap?

**Comment by GinaAbrams** [comment]
ASAP please. There is wrong information on the page right now.

**Comment by kyranjamie** [comment]
@hstove Are you able to deploy the live version? Afaik, the important wrong information has already been updated to $400k, but it isn't deployed.

**Comment by markmhx** [comment]
@kyranjamie Got a PR handy? And has all the information in the document shared by @GinaAbrams been updated or just the $400k figure?

**Comment by kyranjamie** [comment]
Just the 400k number, which is already in `master`

**Comment by markmhx** [comment]
@GinaAbrams I presume the other changes are also urgent, yea?
