### ISSUE TITLE
Text in maker/apps page is confusing

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/app.co#723]
**Describe the bug**
The maker/apps page is divided into three sections --- but the *complete* on the right doesn't make it clear that two things that need to be completed are *subsections* of a section on the primary page:

![image](https://user-images.githubusercontent.com/1347209/70396769-be690880-1a03-11ea-8fc9-c4637d0527ef.png)

This confusing.

**Expected behavior**

This will provide some help for users who are looking to understand the relationships between the sections:

![image](https://user-images.githubusercontent.com/1347209/70396807-359e9c80-1a04-11ea-898f-2ea07d501f92.png)

**Comment by kyranjamie** [comment]
The plan is to merge these last two together, but I suggested doing this once we integrate eversign properly for all the docs.

**Comment by moxiegirl** [comment]
@kyranjamie From an information design purposes, the current layout where all the elements are on the same indention level implies they are at equivalent levels --- this isn't the case. The Tax Documents and SEC are actually not equivalent to "payment details" in how they are presented.  Without entering the email and making a choice -- the user doesn't encounter those headings.  That is why this is confusing.

**Comment by markmhx** [comment]
Agreed this is confusing. We'll fix this UX problem once we've reworked Eversign to set us ourselves up for this change.
