### ISSUE TITLE
[Submit your app] How do I get rid of a particular Blockstack ID?

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/app.co#727]
I don't know how to get rid of this ID, even with a hard refresh:

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/43a5d6d9-1f33-4473-ba11-867eceb92ff6)

We have a design to 'disconnect':

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/75bc9c7b-cb87-43b3-8169-adb9a987061f)

Should we implement this? cc @markmhx

**Comment by markmhx** [comment]
Yes let's definitely implement

**Comment by kyranjamie** [comment]
I'm not so sure on this. 

You "Connect" your ID by signing in. If you want to disconnect it, you sign out. What exactly would happen when you click the X?

**Comment by jasperjansz** [comment]
When you click the X you sign out. When I go to submit my ID is already there:

![image](https://user-images.githubusercontent.com/25477905/70640709-a9c38500-1c3c-11ea-8c7a-6107d9554ca5.png)


What if I don't want to use that ID? How do I sign out/disconnect it?
