### ISSUE TITLE
[Submit your app] Update 'Connect your Blockstack ID' section

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/app.co#728]
We have the following section in the designs:
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/cc6205bb-8a84-4360-9541-16c2e2b54071)

Current implementation:
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/dd7283c7-d993-4ed7-a75f-1fbe4aa1c943)

- The "Connect your Blockstack ID" implies that your app submission will be connected to your ID.
- There is a typo ("it's listing" vs "its listing")
- I'm fine not having the create new ID button and keeping the button as is

**Comment by kyranjamie** [comment]
Added with consistent (old styles)

![image.png](https://images.zenhubusercontent.com/5d765e279cf7af0001b78a5e/f32e5693-e269-4a2b-b383-c394454c2c47)
