### ISSUE TITLE
Fix platform page logic when finding apps

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#73]
Currently, the 'platform' pages only match to Blockchain. We need to change it back to the current logic, which matches on various tags, and allows platforms other than just blockchains.

**Comment by hstove** [comment]
Another issue is that the current version of the 'all platforms' page only includes Blockchains. We need to include all platforms (i.e. storage and auth platforms)

**Comment by markmhx** [comment]
This looks good to me but I'm not sure what the problem was before sooo =)

**Comment by hstove** [comment]
The issue is that Thomas's version only used Blockchains for platform pages, and matched if the app's blockchain was that platform. This change allows any authentication, storage network, or blockchain to be a 'platform'.
