### ISSUE TITLE
Button style is off

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/app.co#737]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/3b6c6e8f-3edb-4491-83e3-434290e7bf6d)

1. The label is misaligned because the line-height is 21px. This is fixed when the line-height is a multiple of 4, just like the button height, such as 24px.
2. The label font-weight is too light compared to our design system:
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/f5aeef94-67b8-45d1-91d3-bdd79ed018f7)

**Comment by markmhx** [comment]
This is no longer relevant.
