### ISSUE TITLE
Fix 'View All' button in list headers

### ISSUE THREAD

**Issue by hstove** [blockstack/app.co#74]
Currently doesn't link anywhere or do anything on click.

**Comment by markmhx** [comment]
The button takes me to its dedicated page now, but when I hit the browser back button, I don't get taken back to the homepage but rather the dedicated page simply reloads.

**Comment by hstove** [comment]
I can't replicate this issue. When I click view all (on home page or 'all platforms/categories' page), it loads correctly, then I click back, and go back to the proper page.

**Comment by markmhx** [comment]
I'll double check

**Comment by markmhx** [comment]
This one seems slippery....seemed to be happening a few minutes ago for me and now can't recreate it. I'll close for now and reopen if I can diagnose better.
