### ISSUE TITLE
[Submenu] ID + sign out wraps to two lines on mobile

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/app.co#744]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/19ddf482-6527-4ec7-b367-81fc9a219883)

We should keep it to one line like in the design:
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/6aa3cf05-93f8-4535-8457-f042b493fdbb)

**Comment by kyranjamie** [comment]
This was an intentional decision to fit in the dropdown when it's present. Indeed, it isn't necessary when the dropdown isn't present
