### ISSUE TITLE
[Manage your apps] Identity verification not opening on mobile

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/app.co#745]
When I tap "Start verification" on mobile it shows "Loading...", but nothing happens

**Comment by kyranjamie** [comment]
This is an issue with Safari, not dissimilar to the issues of opening a new window for the `blockstack-app`

**Comment by kyranjamie** [comment]
Fixed, I've changed the button to a link and performing the async action of fetching the jumio info on load.

The issue was caused because Safari ignores `window.open` calls that are the result of an async action (not a direct onclick event)
