### ISSUE TITLE
Blank screen when opening Participation Agreement on mobile

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/app.co#746]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/01a9b535-d432-4cf8-89ef-e008caa54634)

**Comment by markmhx** [comment]
Let's go new window with this one

**Comment by kyranjamie** [comment]
Closing this issue as implementing in new tab. Relates to issue now in QA #745
