### ISSUE TITLE
When adding documents via dropbox the App Mining submission page completion status does not update 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/app.co#750]
**Describe the bug**
When adding documents via dropbox the App Mining submission page completion status does not update I cannot tell that my documents have been uploaded successfully

Video of issue: https://screencast-o-matic.com/watch/cqlQbqUPwe
**To Reproduce**
1. Go to App Mining submission page
2. Fill out the form correctly and scroll down to Click on legal documents
3. Select the option that I am a US citizen and upload documents via drop box
4. The user is successfully able to upload docs via dropbox but the App Mining submission page does not update and looks as if i still need to submit my docs.

**Expected behavior**
The page should update and show the user that the documents were updated successfully. It seems the hand off from dropbox back to our page was broken in a previous release.

**Screenshots**
<img width="1423" alt="Screen Shot 2019-12-09 at 12 14 31 PM" src="https://user-images.githubusercontent.com/49165468/70457955-214bb580-1a7f-11ea-8ce6-3c56a1de518d.png">

<img width="1421" alt="Screen Shot 2019-12-09 at 12 14 20 PM" src="https://user-images.githubusercontent.com/49165468/70457965-26106980-1a7f-11ea-9ed2-1b8b5770f5b2.png">

<img width="1418" alt="Screen Shot 2019-12-09 at 12 26 50 PM" src="https://user-images.githubusercontent.com/49165468/70457995-34f71c00-1a7f-11ea-9b58-9e32444a8616.png">

**Desktop (please complete the following information):**
 - OS: [10.14.4 iOS]
 - Browser [e.g. chrome Version 78.0.3904.108]

**Comment by FrankyHo** [comment]
I have similar question, how can I check my upload is success? 

<img width="1201" alt="Screenshot 2019-12-13 at 7 02 47 PM" src="https://user-images.githubusercontent.com/35860407/70795853-bdf1b880-1ddb-11ea-8588-7f56e7350f9a.png">

**Comment by kyranjamie** [comment]
@timstackblock The gist here is that, until both the SEC form and tax documents are implemented, the Dropbox upload is a manual step. We've updated the copy to make this clear.

@FrankyHo thanks for your comment. If you're unsure, you can upload the documents again, otherwise hang tight for us to review the documents. We're also soon releasing an update that should improve the maker portal much more user friendly.
