### ISSUE TITLE
app.co/mining/apps not reflecting apps that are eligible 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app.co#758]
**Describe the bug**
This [app](https://app.co/admin/app?id=2575) is marked fully ready for app mining in the admin portal, but not appearing on the website [here](https://app.co/mining/apps)

**Comment by markmhx** [comment]
Could it be because the terms aren't accepted?
<img width="287" alt="Screen Shot 2020-01-24 at 15 33 18" src="https://user-images.githubusercontent.com/28991/73076686-e1ba1b00-3ebe-11ea-8f57-8fe6a75718bf.png">

**Comment by GinaAbrams** [comment]
I dont think so... just checked an app that is listed -- Dmail & showing the same. 
<img width="274" alt="Screen Shot 2020-01-24 at 9 37 41 AM" src="https://user-images.githubusercontent.com/30627583/73077000-452b5500-3e8d-11ea-872b-73eedbd9aea2.png">

**Comment by markmhx** [comment]
The app is showing up now for me. Might have been just a caching issue?
