### ISSUE TITLE
Track page view for username screen / first screen shown

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#761]
![Screen Shot 2020-02-14 at 12.41.52.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/82ab0211-3d2c-4570-8e1f-8c7632bbb683)

**Comment by markmhx** [comment]
@hstove @aulneau same with this one, can you take for @kyranjamie ?

**Comment by aulneau** [comment]
Sure thing

**Comment by hstove** [comment]
Issue moved to [blockstack/app #145](https://github.com/blockstack/app/issues/145) via [**ZenHub**](https://www.zenhub.com/)
