### ISSUE TITLE
Add Fathom tracking script to app.co

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#762]
To start securely tracking data, please add this code to the bottom of your website (or your footer template).

```
<!-- Fathom - simple website analytics - https://usefathom.com -->
<script>
(function(f, a, t, h, o, m){
a[h]=a[h]||function(){
(a[h].q=a[h].q||[]).push(arguments)
};
o=f.createElement('script'),
m=f.getElementsByTagName('script')[0];
o.async=1; o.src=t; o.id='fathom-script';
m.parentNode.insertBefore(o,m)
})(document, window, 'https://cdn.usefathom.com/tracker.js', 'fathom');
fathom('set', 'siteId', 'IVMXEBVJ');
fathom('trackPageview');
</script>
<!-- / Fathom -->
```

**Comment by hstove** [comment]
This is being currently being built for production. It takes a while, so I'll be able to actually deploy tomorrow.

**Comment by hstove** [comment]
This is in production, but I think we need to configure a variable during the project's build process in order for the code we've written to work.

I'm not looking into this at the moment, just putting this comment down and moving back to 'backlog'.

**Comment by markmhx** [comment]
Can @cuevasm now test this on his end given it's in production? Or does the extra variable work mean we're not reporting any data to Fathom yet?

**Comment by cuevasm** [comment]
Isn't detected by Fathom's checker

**Comment by markmhx** [comment]
@hstove any update on this issue? @cuevasm was checking for it again today.

**Comment by cuevasm** [comment]
Yeah I tested again today and fathom isn't picking up when I use the tester to load the page. I also can't find the script in the inspector. blog.app.co is getting picked up with the same tag so I know that works, it's just not counting data from app.co

**Comment by markmhx** [comment]
This should be finished and deployed now.

**Comment by cuevasm** [comment]
Still not registering. I logged in yesterday to test with the Fathom tool and again today. In that time, they seem to have shortened the script, so maybe try that this time? Also, it now says to drop the script in the footer. 

`
<script src="https://cdn.usefathom.com/3.js" site="IVMXEBVJ"></script>
`

In any case, something about the current implementation is not working. I can see Optinmonster just fine so maybe drop it in nearby?

**Comment by cuevasm** [comment]
@pstan26 needs this done asap, what's the status? Can we solve this week please?

**Comment by markmhx** [comment]
@cuevasm Sorry this keeps pushed back to the backlog. Hank is swamped right now with authenticator work though, so this week looks tight. What's the reason for the urgency on @pstan26's end?

**Comment by cuevasm** [comment]
We've been flying blind for 6+ weeks and he would like to know what the traffic levels are right now to make strategic decisions about resourcing this quarter (OKRs)
