### ISSUE TITLE
Connect your Blockstack ID sign in is not working

### ISSUE THREAD

**Issue by yogendrasoni** [blockstack/app.co#763]
**Describe the bug**
on submit app page
Connect your Blockstack ID is not able to connect to blockstack account.

**To Reproduce**
1. goto https://app.co/submit-your-app
2. click on Sign in with blockstack
3. in blockstack browset click on  your id 
**4. It redirects back to submit app form but again shows  sign in with blockstack.**
5. submission of app says "You must sign in with Blockstack"
**Expected behavior**

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: mac os catalina
 - chrome, firefox
 - chrome 80.0.3987.100, firefox 73.0

**Comment by GinaAbrams** [comment]
Thanks for reporting. 🙏 cc @kyranjamie @hstove

**Comment by dxmxnlord** [comment]
I'm having the same problem

**Comment by hstove** [comment]
Should be fixed now 👍

**Comment by dxmxnlord** [comment]
Yup!
