### ISSUE TITLE
January 2020 report not showing

### ISSUE THREAD

**Issue by friedger** [blockstack/app.co#764]
**Describe the bug**
app.co/mining/january-2020 does not show at all

**To Reproduce**
1. open app.co/mining/january-2020 in a browser

**Expected behavior**
Show the list of results

**Screenshots**
![Screenshot from 2020-02-20 08-55-16](https://user-images.githubusercontent.com/1449049/74912328-c7d8fe80-53be-11ea-9b01-1acb6be9d611.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 71

**Additional context**
This is caused by unusual data in https://api.app.co/api/app-mining-months . For January 2020 the BTC payout values and dates are not in the expected format. They are `null` or invalid dates.

![Screenshot from 2020-02-20 08-57-24](https://user-images.githubusercontent.com/1449049/74912474-125a7b00-53bf-11ea-80c7-cddaa52c373b.png)

![Screenshot from 2020-02-20 08-58-26](https://user-images.githubusercontent.com/1449049/74912551-361dc100-53bf-11ea-953c-c3134758687c.png)

**Comment by hstove** [comment]
Fixed, finally!
