### ISSUE TITLE
Remove non-functional Blockstack Board app from app.co

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/app.co#772]
Blockstack Board is no longer around, but is still listed in the browser.blockstack.org landing page under "Business Tools"

![image](https://user-images.githubusercontent.com/52256509/75294733-894ca500-57ff-11ea-8193-a2ebe3a7638a.png)

**Comment by markmhx** [comment]
I'm going to close this out since I believe @cuevasm already plans to do a full audit of apps on App.co to remove those that are no longer hosted. That clean up should cascade to this list of apps on the Blockstack Browser.

**Comment by cuevasm** [comment]
Yep, audit underway
