### ISSUE TITLE
Ensure that app admin pages load

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#773]
e.g. https://app.co/admin/app?id=2829

**Comment by cuevasm** [comment]
None of them load for me at present, here are the first 3 I just tried:
https://app.co/admin/app?id=166
https://app.co/admin/app?id=173
https://app.co/admin/app?id=184

**Comment by hstove** [comment]
Note for admins:

Right now, the only way to log in is on `/submit`. Something happened that broke the login button on `/admin`. Please login at `/submit` first with your admin ID. If you log in through that mechanism, and these are still broken (not just slow), then that's a bug.

**Comment by timstackblock** [comment]
I can get them to load if I go through /submit as explained above.


<img width="1334" alt="Screen Shot 2020-03-02 at 9 43 05 AM" src="https://user-images.githubusercontent.com/49165468/75686488-53c61280-5c6a-11ea-9b8d-ec6faf2a2ef4.png">
<img width="1332" alt="Screen Shot 2020-03-02 at 9 43 19 AM" src="https://user-images.githubusercontent.com/49165468/75686490-545ea900-5c6a-11ea-99b5-1271632ab295.png">
<img width="1329" alt="Screen Shot 2020-03-02 at 9 43 32 AM" src="https://user-images.githubusercontent.com/49165468/75686493-545ea900-5c6a-11ea-874a-62442628c813.png">
