### ISSUE TITLE
Fix CSV download option for admins

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#775]
<img width="323" alt="Screen Shot 2020-02-27 at 13 32 25" src="https://user-images.githubusercontent.com/28991/75445387-9b485800-5965-11ea-8fe6-d3a7f826e4d3.png">

**Comment by hstove** [comment]
Note for admins:

Right now, the only way to log in is on `/submit`. Something happened that broke the login button on `/admin`. Please login at `/submit` first with your admin ID. If you log in through that mechanism, and these are still broken (not just slow), then that's a bug.

**Comment by timstackblock** [comment]
I am able to download the .csv file if I follow your instructions and login through /submit

![Screen Shot 2020-03-02 at 9.45.17 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/47f737bc-f748-443f-8292-61c58bd96052)
