### ISSUE TITLE
Remove Google Analytics tracking script

### ISSUE THREAD

**Issue by cuevasm** [blockstack/app.co#777]
I think this has managed to stick around even though it's supposed to have been removed. Could we please pull it? All that should be on there is Fathom and OptinMonster from our end.

**Comment by markmhx** [comment]
It seemed that our Google destinations in Segment were still enabled but I've just disabled them. Can you verify that Google tracking is no longer showing up for you?

**Comment by cuevasm** [comment]
I'm still seeing this via the tag tool, but could be caching: UA-119163063-1

Will check back in a few hours

**Comment by cuevasm** [comment]
Here's the tag manager I see getting loaded: <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-119163063-1"></script>

**Comment by markmhx** [comment]
@hstove how long might cache take to bust here?

**Comment by markmhx** [comment]
@cuevasm how's it look now?

**Comment by cuevasm** [comment]
Tag manager is still loading: <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-119163063-1"></script>

**Comment by markmhx** [comment]
Ok moving back to the backlog so @hstove can diagnose

**Comment by markmhx** [comment]
This should also have been deployed by now and needs verification in production.

**Comment by markmhx** [comment]
Actually scratch that last comment. IIRC we need to check if we have remnant hard-coded Google Analytics script on the site that needs removal.

**Comment by markmhx** [comment]
@cuevasm I'm not seeing Google Tag Manager anywhere when I inspect the DOM or network requests. Can you check again and specify where you see it if it's still showing up?

**Comment by cuevasm** [comment]
Seems like it's gone now - fathom not loading though

**Comment by timstackblock** [comment]
GTM is gone for me as well but what is this https://a.optmnstr.com/app/js/api.min.js

<img width="373" alt="Screen Shot 2020-04-30 at 9 26 22 AM" src="https://user-images.githubusercontent.com/49165468/80715655-ada95400-8ac4-11ea-8f93-140e06148f27.png">

**Comment by cuevasm** [comment]
That's desired, it's our script for running the little widgets that capture email to the weekly app list

**Comment by cuevasm** [comment]
OptinMonster is the service

**Comment by markmhx** [comment]
Let's close this one out since Google Analytics is gone and track Fathom with https://github.com/blockstack/app.co/issues/762.
