### ISSUE TITLE
Let app descriptions line wrap

### ISSUE THREAD

**Issue by markmhx** [blockstack/app.co#79]
<img width="451" alt="screen shot 2018-07-30 at 13 49 46" src="https://user-images.githubusercontent.com/28991/43395737-6ee5f984-93ff-11e8-9449-0c85f655b4fc.png">
<img width="502" alt="screen shot 2018-07-30 at 13 49 42" src="https://user-images.githubusercontent.com/28991/43395739-6eff09b0-93ff-11e8-87c1-85ec740704af.png">

**Comment by markmhx** [comment]
We seem to have lost this wrapping – not sure why? Moving this back to development.

**Comment by jeffdomke** [comment]
Because I told Thomas to make the change. Some of them become 3 lines long and stretch the entire section out. I don't like short clipped descriptions either but don't think wrapping any amount is the right answer either. Maybe a short description (with a limit) and a long one.

**Comment by markmhx** [comment]
I agree that 3+ lines aren't great so we should find a solution but sense that allowing some stretching for now is better than clipping them to 1 line.

Mind if we make the change back to no wrapping then we can see about editing app descriptions to keep them short enough for now, with the idea of having longer descriptions later?

We'll want long descriptions in any case so users can read more about each app before visiting their pages.
