### ISSUE TITLE
add the Blockstack tag to OpenBazaar

### ISSUE THREAD

**Issue by shea256** [blockstack/app.co#8]

**Comment by shea256** [comment]
@hstove @muneeb-ali pointed out we should remove it if there isn't a clear indication that OpenBazaar is building on Blockstack.

Texted Brian and they said they are adding it to the latest version they're shipping.

But we should play it safe and remove the tag for now and then only add it in if they are clearly using our names for their stores.

**Comment by hstove** [comment]
Sounds good, it's been removed.
