### ISSUE TITLE
Internal service error on page not found

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/app.co#93]
see screenshot
<img width="582" alt="screen shot 2018-08-02 at 9 17 20 pm" src="https://user-images.githubusercontent.com/597182/43586207-965705c0-9699-11e8-9f6b-f33b9a9b7ca6.png">

**Comment by markmhx** [comment]
Did you get to this via direct URL entry or a link somewhere?

I believe https://app.co/platform/blockstack is the only URL for that page in that we haven't removed the "platform" segment yet for these pages.

**Comment by larrysalibra** [comment]
@moxiegirl and were trying to to find the location of this page during our call and were guessing the URL.

The issue isn't the url not existing but the "internal server error" message for a page not found instead of a page not found page.

**Comment by markmhx** [comment]
Ah that's true, we don't have a proper 404 page. @aulneau want to design one and get it integrated?
