### ISSUE TITLE
/categories/all

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app.co#96]

**Comment by jeffdomke** [comment]
See 2 issues here: 
– The header appears blank. No color, no title. 
– The table of categories on top still contains an 'All Categories' button which goes noplace.

**Comment by aulneau** [comment]
just FYI you should be using -> https://appco.now.sh/categories and https://appco.now.sh/platforms (not `/all`)

**Comment by aulneau** [comment]
> – The table of categories on top still contains an 'All Categories' button which goes noplace. 

I opted to keep this button because if someone is navigating on a category page but wants to go back to all, they can hit that button
